### ISSUE TITLE
 File Selection > Package Folder

### ISSUE THREAD

**Issue by freeandroid** [robweber/xbmcbackup#102]
Could this option be added underneath Addon Data?

**Comment by robweber** [comment]
Do you mean like a file selection browser? You could select a specific folder within "addon_data" so you don't get the whole thing, just the ones you want?

**Comment by freeandroid** [comment]
That might work, more options the better right?

Basically I found that the package folder in the addons folder, over time, can get quite large. I personally don't see the need to backup this folder, as my repos are already being back up and I have reliable internet access.

**Comment by robweber** [comment]
Ok, I see what you mean here now. Yea that folder could probably just be excluded. 

I am working on a more generic file selection browser idea but it would still select all directories under a directory you pick. Exclusions in a case like this are important.

**Comment by freeandroid** [comment]
Great! That sounds perfect to me. Thanks Rob!
I really like this plugin, it's saved me so much time over the years :)
