### ISSUE TITLE
French language update for Backup

### ISSUE THREAD

**Issue by bubuleur** [robweber/xbmcbackup#104]
Hello,
I come to you to give you my contribution
The update in French of your addon Backup that I often use
Here is the .xml file
http://www101.zippyshare.com/v/YtugS4C8/file.html
Can put it in your next update
In thanking you
cordially

**Comment by robweber** [comment]
Thanks!

**Comment by bubuleur** [comment]
Hello, nothing you are going to be updated in how long ? 
Thanking you

**Comment by robweber** [comment]
Hopefully soon. I have a few bug fixes that I want to get put in and then do an update specific for Krypton. I just did an update a few weeks ago so I think spacing it by a month is good form.

**Comment by bubuleur** [comment]
Thank you for your reply

**Comment by Logir50250** [comment]
Hello,
I come to you to know if you need me to make a new translation in French for your next version of the addons
Thank you

**Comment by bubuleur** [comment]
f

**Comment by bubuleur** [comment]
Hello, I come back to you for new by 
thanking you

**Comment by bubuleur** [comment]
Hello,
I come back to you for news for the update
In thanking you

**Comment by bubuleur** [comment]
Hello,
I come back to you to have news
Can you answer me
Thank you

**Comment by robweber** [comment]
Getting the language files updated is proving a larger task than I expected. I've been asked by Team Kodi to migration all the legacy .xml files to the now standard .po type files. This is a legit request as the .po standard has been around for some time. As you may notice, there are a lot of language translations for this addon. Just taking time I guess.

**Comment by tmtisfree** [comment]
The .po files are all available on the Transifex website [1], so it is nothing more than a copy. I updated the French strings of your add-on 13 months ago, but none made it in releases so far: the French file still has the outdated XBMC strings in the 1.09 version on the Kodi site.

[1] https://www.transifex.com/teamxbmc/xbmc-addons/script-xbmcbackup/

**Comment by robweber** [comment]
Thank you for that link! I was on the Transifex site a few weeks ago and on the Kodi wiki trying to find information on this. I think my problem is that I was going into the "Kodi Addons" instead of "Xbmc Addons". I had thought they needed to be manually done, I even posted on the forum. Appreciate you pointing this out.

**Comment by bubuleur** [comment]
Ok thank you for your reply
The problem will be corrected in your next update?
Cordially

**Comment by tmtisfree** [comment]
If what you want is just an update with the French translation, here is it:
[script.xbmcbackup-1.0.9.1.zip](https://github.com/robweber/xbmcbackup/files/973061/script.xbmcbackup-1.0.9.1.zip)

**Comment by bubuleur** [comment]
Thank you for your file but you know if in the next update the file of French language will be updated
cordially

**Comment by robweber** [comment]
I'm going to try and get to updating the translations with the PO files within the next 2 weeks. Kind of a long timeline but "gotta work the day job" too.
