### ISSUE TITLE
BackUp Error

### ISSUE THREAD

**Issue by W4CROBSTER** [robweber/xbmcbackup#105]
I never had any problems backing up a build but then started about week ago when i hit back up it goes through the process but its at 96 % where it say cache/temp then it stops there for about 10 sec then it says Check The Log For More Information. do u happen to know what log i need to log into and what i need to fix?

Thanks
Robert

**Comment by robweber** [comment]
It should just be the regular Kodi log file, make make sure you enable debug mode in the settings to get all the log entries. 

Not sure exactly where this will be on your system, but this site has the paths for various OSes. http://kodi.wiki/view/Log_file/Advanced

**Comment by akiskall** [comment]
I don't want to hijack this existing issue but i'm having a similar problem and it's best not to create a new one.

This is what i get in my kodi.log whenever i try to backup:

14:05:40.799 T:1583346608   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: Unknown exception thrown from the call "read"
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/script.xbmcbackup/default.py", line 73, in <module>
                                                backup.run(mode)
                                              File "/home/pi/.kodi/addons/script.xbmcbackup/resources/lib/backup.py", line 256, in run
                                                filesCopied = self.backupFiles(fileGroup['files'],self.xbmc_vfs,self.remote_vfs)
                                              File "/home/pi/.kodi/addons/script.xbmcbackup/resources/lib/backup.py", line 482, in backupFiles
                                                wroteFile = dest.put(aFile,dest.root_path + aFile[len(source.root_path):])
                                              File "/home/pi/.kodi/addons/script.xbmcbackup/resources/lib/vfs.py", line 97, in put
                                                self.zip.writestr(utils.encode(dest),aFile.read())
                                            RuntimeError: Unknown exception thrown from the call "read"
                                            -->End of Python script error report<--

If i disable the addons backup then this error goes away and the process completes successfully. Something is going wrong with xb,cbackup and my collection of addons. 

I'm having the latest version of xbmcbackup

Thanks in advance!

**Comment by robweber** [comment]
Not really sure what to do with this one, looks platform specific. Could be a unicode problem but I'd have to know if you're using a non-english language that might have non-unicode filename characters. That does seem to cause issues.
