### ISSUE TITLE
Server Auth

### ISSUE THREAD

**Issue by unlocKing** [robweber/xbmcbackup#106]
Would it be possible to add a simple username/password in the 'Remote Path Type' settings for logging into my server?

Cheers!

**Comment by robweber** [comment]
What remote path type are you using? You should be able to insert usernames and passwords if typing a path - examples liked this: http://kodi.wiki/view/List_of_media_source_types 

Does that help?

**Comment by unlocKing** [comment]
Remote path is a directory on my site

**Comment by robweber** [comment]
So it's like an http site? What prevents you from just using http://username:password@ip/path as listed [here](http://kodi.wiki/view/List_of_media_source_types#HTTP_.28Hypertext_Transfer_Protocol_.29_Client)

**Comment by unlocKing** [comment]
When the password changes, it's easier to have a box pop up asking for new password.

**Comment by robweber** [comment]
After looking into to it I can't really get any reliable way of knowing if the connection failed for a password issue or just the whole path is wrong. Kodi's vfs system is kind of a success/failure sort of thing. Prompting for a password when really the whole path is incorrect wouldn't make a lot of sense. I'd do it if I could, but I'm just not given the right info after the "connect" call.
