### ISSUE TITLE
By default, backup any not default kodi folder in special://profile

### ISSUE THREAD

**Issue by freMea** [robweber/xbmcbackup#108]
App version | OS | Kodi
------------------ | ---- | ---
commit 2927e31 | Win 10 x64 pro (french) 14393 | 17.3

I expect it backup only the needed files plus the user one without having to define them as custom if they are in `special://profile` root. That is to say, auto include folders in `special://profile` that are not the kodi default one (since those folders should have been added by the user for a reason and must be backed up). 

For instance, `special://profile/vignettes/` is a custom path where I put some special thumbnails I use for my favourites. This is very handy since I can easily refer to it in any config file like favourites.xml like:

```
<favourites>
    <favourite name="Top 250" thumb="special://profile/vignettes/top250.jpg">ActivateWindow(10025,&quot;special://profile/playlists/video/Top 250.xsp&quot;)</favourite>
… etc.
```

**Comment by robweber** [comment]
Going to close this, but not because it's invalid. I'm merging a lot of issues into on PR https://github.com/robweber/xbmcbackup/pull/117
