### ISSUE TITLE
Setting a GDrive authorization fails if settings not saved one time

### ISSUE THREAD

**Issue by freMea** [robweber/xbmcbackup#110]
App version | OS | Kodi
------------------ | ---- | ---
commit 2927e31 | Win 10 x64 pro (french) 14393 | 17.3

## Steps to reproduce

1. Enter Addon settings
2. Select Google drive as remote path
3. Client ID & secret MUST be empty
4. Fill the client ID & secret
5. Run **Authorize Now**

## Results

The generated url is missing client ID and results as:
`https://accounts.google.com/o/oauth2/auth?scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.file&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&client_id=&access_type=offline`

## Workaround

After you have set your client ID & secret, you have to save the settings and reopen them to run the **Authorize Now**. The url will be ok.

**Comment by robweber** [comment]
There was a catch for missing key/secret but because of where it was it didn't really do anything. Nice catch. Thanks.
