### ISSUE TITLE
Error accessing GDrive: attribute of type 'NoneType' is not callable

### ISSUE THREAD

**Issue by freMea** [robweber/xbmcbackup#111]
App version | OS | Kodi
------------------ | ---- | ---
commit 2927e31 | Win 10 x64 pro (french) 14393 | 17.3

## Steps to reproduce

1. Set and authorize GDrive account
2. Enable Drive API for your project
3. Run backup

## Results

It fails to connect.
Error [attribute of type 'NoneType' is not callable](https://paste.ubuntu.com/25267834/)

**Comment by robweber** [comment]
Pretty sure this is actually a symptom of the oauth2client library. I had it myself and noticed a pull request from someone else for a fix. I applied it to my local setup and everything is working now. I'm going to push that addon to the Kodi lib. Here is the request for reference: https://github.com/robweber/script.module.oauth2client/pull/1
