### ISSUE TITLE
Readme provides a dead link for Google API client setup

### ISSUE THREAD

**Issue by leeds55** [robweber/xbmcbackup#113]
Under the **Using Google Drive** heading, the link https://developers.google.com/drive/web/quickstart/quickstart-python is now dead.  

I think https://developers.google.com/google-apps/realtime/realtime-quickstart, perhaps more specifically https://console.developers.google.com/start/api?id=drive may be the new most appropriate link, but I'm not getting the tinyurl to generate the validation code after inputting the client ID & client secret, so it seems I'm not doing something quite right anyway.

**Comment by robweber** [comment]
I think this might actually be the right one, as it's python specific. I'm having some issues with the GDrive stuff as well after authentication passes so I think more than just that has changed on the Google Side. 

https://developers.google.com/api-client-library/python/start/get_started
