### ISSUE TITLE
dropbox api version

### ISSUE THREAD

**Issue by eddavidson** [robweber/xbmcbackup#114]
Hi there, I can no longer upload to dropbox. Here is my log:
https://www.dropbox.com/s/uokmaw8ycrmd4ai/backup.log?dl=1

Looks like they have changed the API

**Comment by Paul-Reed** [comment]
Yes, found the same issue. 
Dropbox api is now v2, and they have now switched off v1 so this no longer works.

**Comment by robweber** [comment]
I'll have to update. Was working my way down this list and got Google Drive back up and running.

**Comment by robweber** [comment]
Took a while but I think Dropbox v2 is working now. Did test authorize, backups, and restores. Not confident enough to push to master so please test if interested. You'll most likely have to remake your Dropbox Secret/Key in the app area on Dropbox Developer. 

https://github.com/robweber/xbmcbackup/tree/dropbox_v2

**Comment by eddavidson** [comment]
I will try it. Thanks.

**Comment by madeira83** [comment]
Hi,
I tried the fix for the dropbox v2 api. The backup option works! But when i try the restore option i am able to see all of my folders that i can restore from but when i select them i get: "Error: Remote path doesnt exist/{path name}/".

**Comment by robweber** [comment]
Interesting, I had both backups and restores working for me. Can you provide a log, please post to somewhere like https://pastebin.com/  and provide a link.

**Comment by madeira83** [comment]
Here is the log. I logged it with debug off and then tried it with debug on.
https://pastebin.com/pUcM7BrS

**Comment by eddavidson** [comment]
Recently getting this error. 
16:19:34.689 T:2964321184   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named apiclient.discovery
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.librarybackup/scheduler.py", line 9, in <module>
                                                from resources.lib.backup import XbmcBackup
                                              File "/storage/.kodi/addons/script.librarybackup/resources/lib/backup.py", line 7, in <module>
                                                from vfs import XBMCFileSystem,DropboxFileSystem,ZipFileSystem,GoogleDriveFilesystem
                                              File "/storage/.kodi/addons/script.librarybackup/resources/lib/vfs.py", line 9, in <module>
                                                from pydrive.auth import GoogleAuth
                                              File "/storage/.kodi/addons/script.librarybackup/resources/lib/pydrive/auth.py", line 6, in <module>
                                                from apiclient.discovery import build
                                            ImportError: No module named apiclient.discovery
                                            -->End of Python script error report<--

**Comment by robweber** [comment]
@eddavidson  - last error related to #120. I'll keep updates about it there.

**Comment by robweber** [comment]
I've merged this in with master and pushed to repo. Any issues can be ironed out after. I've tried from 3 different platforms, both backup and restore, with no issues.

**Comment by madeira83** [comment]
What could be causing my issue?

**Comment by robweber** [comment]
@madeira83 - I think the last commit I made here should fix the issue you were experiencing. Please let me know and I'll close this out. All Dropbox v2 functionality should be there now.

**Comment by robweber** [comment]
Going to close this out - changes are all merged into the Kodi repo and should be available for all users now.
