### ISSUE TITLE
.strm files doesn't backup

### ISSUE THREAD

**Issue by FabrizioA** [robweber/xbmcbackup#115]
Hi,

I've noticed the all .strm files inside "videos" and "tvshows" folders doesn't backup.
It's a normal behavior?
Thank you.

**Comment by robweber** [comment]
Are you listing TVshows and Videos as custom folders? No reason those files shouldn't be included. I can do some testing though.

**Comment by robweber** [comment]
I tested this a few times and always got the .strm files to copy over. Going to close this but feel free to reopen if it's still happening

__Note__: I'm using the current master branch for testing.
