### ISSUE TITLE
Restores Not Being Found

### ISSUE THREAD

**Issue by robweber** [robweber/xbmcbackup#125]
Issue: backups not being shown when selecting "Restore" option with latest master version. 

From @seanboy 201: 

Yes i installed. The newest one u gave. Me but problem im having is that
when i got to restore it says the directory i chose is empty. Even though
its the same directory i always use to compleate the backup

**Comment by robweber** [comment]
To work on this I'll probably need some info. 

1. What are you using as your target? Shared drive, Dropbox, Google drive, etc? 
2. When did you create the backups? 
3. Do the xbmcbackup.val files exist in each of the archives? The program won't list them without this. 
4. Debug log

The code for listing the restores hasn't really changed for a long time (unless you've pulled the Krypton branch, that is a complete rewrite). As long as the folders are accessible they should be listed. I would also try just making a new backup and seeing if you can see it afterwards.

**Comment by robweber** [comment]
@seanboy201 - any update on this? Is this still happening with the latest master branch?

**Comment by seanboy201** [comment]
I got it working now .. Thanks alot bud... May have to get u to send file
one more time at a later. Date as im dowm and sick right now... Happy new
years to u and your family.. God bless
