### ISSUE TITLE
Installation of Add on

### ISSUE THREAD

**Issue by Paul-Reed** [robweber/xbmcbackup#128]
Quick question Rob, how is this installed please? Is it available from a separate repo...

**Comment by robweber** [comment]
It's in the official Kodi repo listed as "Backup" under the Programs area of the Addon Browser. Here [is a link](https://kodi.tv/addon/program-add-ons-scripts/backup) to the addon page of the Kodi site. I'd install through Kodi though as you'll get the dependencies then.

**Comment by Paul-Reed** [comment]
Thank you
