### ISSUE TITLE
Dropbox destination not writable

### ISSUE THREAD

**Issue by Paul-Reed** [robweber/xbmcbackup#129]
Have just set up Dropbox as my remote, as per the readme, and got confirmation in Kody that my app had been authorized by Dropbox. However, when I run backup, I can see that various files are being added to the archive, but eventually I get the message shown below saying that the destination is not writable, and the archive is not uploaded.
I've rechecked my app key & secret (although as it has been authorized, I assume that they must be correct), and the Dropbox status is `Development`.

![dropboxphotos](https://user-images.githubusercontent.com/973580/34391780-c8bd0ef2-eb3f-11e7-9b12-9caf60c61956.jpg)

**Comment by Paul-Reed** [comment]
**Update** - if I select the option to backup the files to Dropbox, instead if a compressed file archive, the add-on works as expected.
I'm not sure of the overall uncompressed size of my backup (as it's still uploading), but could this be some sort of Dropbox time-out issue??

**Comment by Paul-Reed** [comment]
**Update 2** - checked this morning and the total size of the backed-up data is 304Mb.
Assuming it is a Dropbox timeout that causes the error, is backup using [upload_session](https://www.dropbox.com/developers/documentation/http/documentation#files-upload_session-start) to manage the upload?
[This post](https://www.dropboxforum.com/t5/API-support/API-Upload-Limit/td-p/204372) in the dropbox forum discusses large file upload options.

**Comment by robweber** [comment]
I think you're on the right track there. Adding session support didn't take too much effort. I split the files at 25MB rather than the Dropbox max of 150. I may increase this to 50MB before merging in. I tried a 180MB file as a test and it worked just fine. 

If you want to test the only file modified is the vfs.py file. You can safely replace the one on your system with that and try it out.

**Comment by Paul-Reed** [comment]
I've just tried your changes to the vfs.py file, and made a successful archive backup to dropbox with no problems.
The archive is 262Mb in size (uncompressed 304Mb).
Also tried increasing the chunk filesize to 50Mb, and again worked flawlessly.

Nice work Rob!

**Comment by robweber** [comment]
Glad it worked. I modified it to 50 by default and merged it in. Probably won't make the repo for a bit though as I just did a pull request recently.
