### ISSUE TITLE
ability to add excluded path(s), cron question

### ISSUE THREAD

**Issue by mgonzales71** [robweber/xbmcbackup#131]
I want to backup user_data/* except 2 directories that contain cache info (simplecache by marcelveld for example)
if I were to use advanced not only would that take forever but it would need to be updated for any new directories that are added.
unless I am missing something obvious here could you consider this for a future update?
thanks!

also

I was curious if your cron scheduling implementation had the ability to do for instance:
every 3 days ... like using 1-31/3 or just /3?

Thanks!

Mario

**Comment by robweber** [comment]
When you say "use advanced" are you talking the Advanced mode in the Krypton branch I'm currently working on? It's totally useable at the moment and I have a list of features on the (pull request)[https://github.com/robweber/xbmcbackup/pull/117].  With that mode you can add the entire user_data directory and then simply exclude the 2 directories you mention. It would always detect new directories, just exclude the others. 

As far as cron goes you can do what you're asking with the implementation here. Something like: 

```
0 0 */3 * *

or

0 0 * * 1,4
```

Pretty sure both of those would work.

**Comment by mgonzales71** [comment]
yea - using your latest dev code, sorry for that confusion.

I will give the advanced mode a try as you suggested - and I know its dev code so I won't whine if I mess up my backups LOL  - thank you.

also thanks for the cron tip -  I had not tried */3 - just /3  

Mario

**Comment by mgonzales71** [comment]
ok - cool works like a charm with */3 - thanks!

have one other request for future consideration but I will close this and open another to keep things tidy.
