### ISSUE TITLE
request: in advanced backup selection, include predefined "simple" options

### ISSUE THREAD

**Issue by mgonzales71** [robweber/xbmcbackup#132]
If you would please consider adding the following for https://github.com/robweber/xbmcbackup/pull/117

what I mean is - it would be nice to be able to choose the options in "simple" mode as per-defined items from a list to then modify  while in advanced mode.

or - maybe an edit in advanced mode if you have already defined backup selections in simple mode.

I think including the simple selections as options in advanced mode would be preferred.

Thanks again love and appreciate you work!

Mario

**Comment by robweber** [comment]
I agree some kind of defaults for the advanced viewer would be nice. If for no other reason than to show how the setup of that all works. I'll think about this and see what I can come up with.  I like your idea of copying from the simple mode settings.

**Comment by mgonzales71** [comment]
I have been playing around with advanced file selection in the krypton branch

using code from this commit (not the WIP for #132)

https://github.com/robweber/xbmcbackup/commit/adbf225ea2a1d9faf840764021df2797610340f3

is this possible:

backup:

root/foo/*
(recurse include)

but exclude:
root/foo1/sun/
root/foo1/moon/

seems to not work or I can't make it work

adding subfolders of the root of the backup set to be excluded seem to be ignored.

no biggie I just had time to test it out more today 

do you have any docs for what all you can use in the json file?

Thanks

**Comment by robweber** [comment]
going to close this out and this particular issue is now taken care of in the current branch. One thing I did double test is the example of doing a root of `/root/foo` and excluding a sub directory like `/root/foo/sub1`. Based on the most current branch for this update it was excluding the subs as expected.
