### ISSUE TITLE
Android Non-compressed Backups and MediaScanner

### ISSUE THREAD

**Issue by nyetloki** [robweber/xbmcbackup#135]
Android will scan any folder on it's media (internal storage, external sd, external hard drives) for images and videos. It does not do it for the internal storage/Android/data/ directory, where the XBMC/Kodi/CEMC profile is. The profile which has the Thumbnails. Because it has a .nomedia file at internal/Android/data/.nomedia.

**XBMCBackup puts these in Downloads. If uncompressed, it will cause high cpu and crud up the Android Gallery with all the thumbnails and add-ons files.** There is a delay with too many files on a drive, as MediaScanner must scan everything.

Simple solution is adding a .nomedia file (blank file) to the folder you want to exclude from MediaScanner.

**Requesting** that this be added as an option to XBMCBackup. Simply create a .nomedia for any backups that are uncompressed at the root of the folder (/path/to/backup/201801012233/.nomedia). You could also do it for the compressed ones without any issue.

**Comment by robweber** [comment]
Good catch, I don't use Kodi on Android myself so this was never something I noticed. So adding the .nomedia to the root of the backup folder will kill that scan process? That's a pretty simple thing to add in. I'll tag this comment when committed if you want to test it out.

**Comment by nyetloki** [comment]
Correct. See https://developer.android.com/guide/topics/data/data-storage.html#filesExternal for Google's official explanation for the .nomedia file. I'll be happy to test it :)

**Comment by robweber** [comment]
Hopefully that commit does it. Tested it and I got a .nomedia file in the root of the backup folder.

**Comment by robweber** [comment]
Any update on this? Pretty minor change so I don't mind merging it in but would like to know it works.

**Comment by nyetloki** [comment]
works great.
