### ISSUE TITLE
[Feature Request] Expert Web Based Backup Set Config

### ISSUE THREAD

**Issue by mgonzales71** [robweber/xbmcbackup#136]
Obviously a request for some other iteration of this awesome add on.

But it is on the roadmap to have some basic html based functionality in a future version of kodi so maybe not too far off.

But the ability to configure and setup backup sets via a web based expert mode with the entire file system exposed, etc.

something more akin to:

![](https://www.duplicati.com/images/news/2016-03-20-New-SourcePicker.jpg)

**Comment by robweber** [comment]
I would love to add a more visual editor like what you have here. Right now the enhancements in the ongoing pull request I have going are about as advanced as I can get at the moment. What I can create in the Kodi gui is definitely a limitation at the moment. A custom gui is an option but not one I like. Those break with every different skin out there and become a real pain to maintain. 
This might be open for a long while but a good reminder of something to shoot for.

**Comment by mgonzales71** [comment]
Oh I didn’t expect it would be something you would be adding tomorrow :)  hehe

Just was looking at few different python web app frameworks the other night... cherrypy, web2py, etc and thought it could be a way to overcome the the problem of skins and GUI the associated limitations in Kodi.  

Wanted to throw it out there before it got shuffled to bottom of my mental pile.

It’s clunky yea but honestly a lot less so then trying to work in the limitation of what is available now.

Thanks for the consideration and your work with this add on

Mario

**Comment by mgonzales71** [comment]
Oh forgot to mention which is obviously way overkill for this add on but I had run across while looking around the other night.

https://github.com/ziirish/burp-ui

Has a cool Web app Demo site

https://demo.burp-ui.org/login?next=%2F

Anyway 

Thanks again and have a good evening 

Mario

**Comment by robweber** [comment]
I think this is mostly solved by the Advanced Editor.
