### ISSUE TITLE
Google Drive authorization fails and requests "developer code"

### ISSUE THREAD

**Issue by ratchetchan** [robweber/xbmcbackup#141]
Exactly what the title says. After the valid Client ID and Secret are input and authorization is commenced, it produces a window saying: "Google Drive Developer Code Needed / visit https://console.developers.google.com" as if one hasn't just left that page to get the information. Furthermore, no such thing as a "Google Drive Developer Code" is seen on that page nor in a Google search for that exact term.

**Comment by robweber** [comment]
I'm guessing you put in the ID and Secret and then tried to hit "authorize"? This is a quirk of how the Kodi settings menus work. They don't actually set any values until you hit OK. What ends up happening is that when you hit authorize it pulls in the two key values but they come in blank. You have to hit OK and then go back in an hit authorize. Kind of stupid, I'll agree. Just part of how the Kodi settings dialogs work. 

Please try that and see if you have the same issue.

**Comment by robweber** [comment]
Assuming this fix worked for you. I've tested drive functionality just today and it worked.

**Comment by ashleyw** [comment]
As soon as I click Okay and try and re-open the settings to authorize, I get the message "Authorize this remote service in the settings first" 🤔

**Comment by robweber** [comment]
Try re-opening the settings through the context menu. My guess is you're trying to run the app directly to get the "open settings" dialog option? When launching the program first it's doing some verification. Probably should bypass this if you click the settings option. Let me know if this fixes it and I'll create an Issue for this specifically.

**Comment by gallo2000sv** [comment]
Hi, I know it's been a few months but this is exactly happening to me. Not only in this addon but in another. 
I tried your solutions and still keep showing me: "Authorize this remote service in the settings first" when i try to open the addon

**Comment by robweber** [comment]
Did you find the solutions from [the wiki](https://github.com/robweber/xbmcbackup/wiki/Google-Drive)? Do those instructions work?

**Comment by megadroided** [comment]
i get the developer code enter it and then it fails.... running latest kodi build

**Comment by robweber** [comment]
Can you tell me what version of Backup you're using? The most current version of Kodi (Matrix) uses Python 3; and all Python 3 builds of the Backup addon don't include support for Google Drive as a cloud provider. Depending on what you're running it might just be a compatibility problem. 

Google drive support was [removed in 1.6.0](https://github.com/robweber/xbmcbackup/blob/matrix/changelog.md#version-160---2019-11-26)
