### ISSUE TITLE
Error on GuiSettings Restore

### ISSUE THREAD

**Issue by robweber** [robweber/xbmcbackup#162]
**Describe the problem**
From [elhifinio on the Kodi Forum](https://forum.kodi.tv/showthread.php?tid=129499&pid=2904177#pid2904177): 

> no matter which version I am using (1.1.3, 1.5.0 or 1.5.2) I do get the following error (see log). Regional settings are German. 

**Platform and Kodi version**
I am using Kodi 17.6 x64 on Windows 10.

**Link to Debug Log**
[Log 1](https://paste.kodi.tv/udonuqeyah.kodi)
[Log 2](https://paste.kodi.tv/anecoreviq.kodi)

**Comment by robweber** [comment]
Log 2 seems to be a different error than the first one (because of the fix I tried earlier). Now the JSON lib is saying the result is not a JSON string that can be decoded. 

I added an extra logging line to the branch that will print out the full text string from the GetSettings command. Hopefully that will show where things are going wrong. Also as a plus, once I have the string I can hardcode it into my testing and try things without needing you to constantly download zip files and test them. 

Please download the latest zip from the [testing branch](https://github.com/robweber/xbmcbackup/tree/krypton_guisettings_fix) and try it.

**Comment by ac-bra** [comment]
I created a new Github account, I am elhifinio from Kodi forum.

**Comment by robweber** [comment]
On line 10 if you[ latest log ](https://paste.kodi.tv/awikodupig.kodi)I do see in the debug section that the GetSettings JSON call is going through. 

I think you might be on to something with that filterconfig xml error. Do you know what that file does, does it even exist? Maybe try renaming it to filterconfig2.xml and restart Kodi. You can always put it back. I'm wondering if when trying to load the GuiSettings information it's trying to read that file and since it's throwing an error isn't returning the proper JSON response?

**Comment by ac-bra** [comment]
this file is installed in C:\Program Files\Kodi\system\players\dsplayer containing this [https://paste.kodi.tv/iseketahev](url). After renaming it, backup and restore the error remains the same.

**Comment by robweber** [comment]
I was taking another look at one of the logs you posted and saw this error: 

```
18:27:45.119 T:12096   DEBUG: Unicode Error
```
That occurs roughly where I'd expect the log line I was hoping to see should show up. I messed around with the code a bit and think I may have a fix. If you want to download from the [guisettings_fix branch](https://github.com/robweber/xbmcbackup/tree/krypton_guisettings_fix) again and try it I'm hoping it will get things working for you.

**Comment by ac-bra** [comment]
Unfortunately, still do have the same issue: https://paste.kodi.tv/akalumutov.kodi

**Comment by robweber** [comment]
Thanks for trying that, at least the error is different now: 

```
UnicodeDecodeError: 'utf8' codec can't decode byte 0x92 in position 85758: invalid start byte
```

I did some digging on that and 0x92 is a [Windows specific character](https://stackoverflow.com/questions/29419322/unicodedecodeerror-utf8-codec-cant-decode-byte-0x92-in-position-377826-inva) that has no utf-8 replacement. I guess at least we're narrowing down the problem. I'll think a bit on what (if anything) can be done about that.

**Comment by robweber** [comment]
I'm not sure this is the most elegant solution but I pushed another fix to the branch where I'm attempting to just ignore decoding errors. This might get the string to decode and keep things moving.  If you're up for it give it another shot. 

These issues are always kind of tricky. Here is a [link to a good explanation](https://github.com/romanvm/kodi.six/issues/3#issuecomment-530756498) from romanvm on how Kodi does things behind the scenes with character encodings. We might fix this one problem but once Kodi moves to Python3 we'll have a whole other set of encoding issues. Let me know what happens.

**Comment by ac-bra** [comment]
Just tried to install the new version but while installation I do get the following error: 

`15:38:51.795 T:3720   ERROR: CAddonInstallJob[script.xbmcbackup]: Die Abhängigkeit auf script.module.dropbox in Version 9.4.0 konnte nicht aufgelöst werden.`

Seems to be some Dropbox dependencies cannot be resolved :/

**Comment by robweber** [comment]
Are you installing from this branch - that branch doesn't use dropbox 9.4.0. In master and matrix (py3 only) that is a new dependency. 

https://github.com/robweber/xbmcbackup/tree/krypton_guisettings_fix

**Comment by ac-bra** [comment]
now it works, thank you :)

**Comment by robweber** [comment]
That's great. I can merge this fix down into the Krypton branch. I'm unsure how this will play out with the python3 version. Strings are handled differently there and the ```decode()``` function doesn't even exist. I'll have to see if I can come up with a test for that. 

I'll leave this open for a bit until I merge everything so I don't forget.

**Comment by ac-bra** [comment]
great, thank you Rob
