### ISSUE TITLE
Dropbox and Google Backup 

### ISSUE THREAD

**Issue by Tiemichael** [robweber/xbmcbackup#174]
I wanted to use  Cloud Saving  for this plugin but failed:
1) Dropbox: after entering the App Key and App Secret and 'OK', when asking for authentication I receive some error-message
Here is the relevant entry to the kodi-log:

`2020-12-15 15:43:08.861 T:6324    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: function takes at most 2 arguments (3 given)
                                                   Traceback (most recent call last):
                                                     File "/home/michael/.kodi/addons/script.xbmcbackup/launcher.py", line 51, in <module>
                                                       authorize_cloud(params['provider'])
                                                     File "/home/michael/.kodi/addons/script.xbmcbackup/launcher.py", line 16, in authorize_cloud
                                                       if(authorizer.authorize()):
                                                     File "/home/michael/.kodi/addons/script.xbmcbackup/resources/lib/authorizers.py", line 41, in authorize
                                                       if(not self.setup()):
                                                     File "/home/michael/.kodi/addons/script.xbmcbackup/resources/lib/authorizers.py", line 27, in setup
                                                       xbmcgui.Dialog().ok(utils.getString(30010), utils.getString(30027) + ' ' + utils.getString(30058), utils.getString(30059))
                                                   TypeError: function takes at most 2 arguments (3 given)
                                                   -->End of Python script error report<--
                                                   
2020-12-15 15:43:09.905 T:6324     INFO <general>: Python interpreter stopped
`

2) Google Drive: there is no option for this available

I am using: Backup version="1.6.3", with Kodi Matrix 19beta2, on a Jetson Nano running Ubuntu20.04

**Comment by robweber** [comment]
I'll take a look at this. There were some changes to the ```xbmcgui.Dialog()``` class with Matrix. I thought I had caught them all but guess I missed one.

**Comment by robweber** [comment]
I think I have this working now. I was able to get the entire Dropbox flow working for me. Do you have the ability to test by downloading a zip from the ```matrix``` branch? If not I'll push to the repo but another verification would always be helpful!

**Comment by Tiemichael** [comment]
Thanks! Dropbox is working with the  new version!

The option to use 'Google Drive' is still not available....

**Comment by robweber** [comment]
Great - glad that's working. 

Google Drive is not available on Kodi Matrix due to a lack of Python3 compatible libraries. It may be added in the future but as of now it had to be stripped out. You shouldn't even see that as an available option in the settings. Given that Matrix isn't the current stable release the documentation for this hasn't been updated.

**Comment by Tiemichael** [comment]
Thank you for the update!
