### ISSUE TITLE
Extremely slow write SMB

### ISSUE THREAD

**Issue by Nehemoth** [robweber/xbmcbackup#184]
I'm using the 1.6.4 version with Kodi 19 which it's working now.
The backup complete successfully on the Nvidia Shield but when it has to write the information in the shared disk using SMB it does so in extremely slow fashion.

It worked before with Kodi 18.9 without any issue.

Having said that, I'm reporting here but I'm pretty sure that this has something to do with SMB in Kodi v19
It's painfully slow even for access.

**Comment by robweber** [comment]
I'm going to agree with you it's got to either be a Kodi thing or something with the SMB share itself. This addon uses the built in Kodi VFS file system to do the read/write operations. Everything is passed off to lower level Kodi C++ code to do the actual data transfers.
