### ISSUE TITLE
Unable to add Remote Path

### ISSUE THREAD

**Issue by CiNcH83** [robweber/xbmcbackup#193]
**Describe the problem**
When trying to add a path, the browser lacks several entries, like for example _Zerconf browser_ or _Add network location..._:
![image](https://user-images.githubusercontent.com/24539361/121637565-dbafe480-ca89-11eb-84cc-3095fefa28d9.png)

In Kodi's own _File manager_, those entries are available:
![image](https://user-images.githubusercontent.com/24539361/121637778-38130400-ca8a-11eb-8144-a42d1874b004.png)

This makes the addon pretty much unusable for me as I can't find a way to add a network path as SMB shares can only be added via _Zeroconf browser_ on Android.

**Platform and Kodi version**
Android TV 9
Kodi 19.1
Backup 1.6.7

Tell me whether a log will help.

**Comment by CiNcH83** [comment]
Now worked around it by sharing the folder via insecure NFS.

**Comment by robweber** [comment]
You couldn't select "Windows network (SMB)" and browse for the share? The naming is confusing (this is Kodi's dialog, not mine) but that entry means any SMB share; no matter the hosting source. You should be able to select that and browse from there. Add Network Location is missing as this dialog isn't for adding anything as a source for video/music. You'll need to browse to the path and then hit OK to fill in the path name. If I'm not following this right please let me know. 

If Zeroconf is your only option for Android related to browsing could you use the "type path" option and just type the full path that way "smb://......"?

**Comment by CiNcH83** [comment]
> You couldn't select "Windows network (SMB)" and browse for the share?

No. That doesn't work on Android, also see [here](https://forum.kodi.tv/showthread.php?tid=331190).

> If Zeroconf is your only option for Android related to browsing could you use the "type path" option and just type the full path that way "smb://......"?

Would have to try this. Why is there no _Zeroconf browser_ available for the addon?

I think I will stay with NFS. I can publish the Kodi backup shared folder without putting other data at risk.

**Comment by robweber** [comment]
Interesting - I don't use SMB myself so didn't realize the browse option only worked for SMBv1. Makes sense. 

I am at a loss about why Zeroconf browser doesn't show up. I'm not coding anything to do with the file browser, I'm simply [asking Kodi to launch one](https://github.com/robweber/xbmcbackup/blob/matrix/resources/settings.xml#L88). It could be that the internal components of Kodi just aren't allowing it to appear. Issues with this in the past are what lead to the "type path" option being available. Cross platform solutions for network service browsing aren't always reliable. 

One thing I did try that seemed to work was adding the `<source>files</source>` tag to the path option. This doesn't add the Zeroconf browser but it does bring in any saved paths from the File Manager to the root nav. You could use the File Manager to add the path you want and then it would appear in Backup browser as a selectable source. I think this could be a workable solution.

**Comment by CiNcH83** [comment]
Zeroconf browser has always worked for me with Backup. Only now with 19.1 and 1.6.7 it does not anymore. Thought the problem might be similar to [this](https://github.com/CastagnaIT/plugin.video.netflix/commit/4c8359bfd846a493d32891245129f23c995ccc6f).

**Comment by robweber** [comment]
I couldn't find any combination of the `local`, `programs`, `video`, etc [options](https://kodi.wiki/view/Add-on_settings_conversion#type.3D.22folder.22) that put it back. Either something with the new settings system or just removed with Kodi 19. It definitely exists in the "Add Source" option but not in the addon file browser. I think adding it as a source for the File Manager is a good workaround - or at least the best we can do for now.

**Comment by CiNcH83** [comment]
I tested the workaround and it seems to work. The browser shows NFS and SMB paths after having been added through File manager. It however does not show FTP paths for some reason.

(I now decided against using NFS for Backup as it contains username and password of my NAS in clear text. SMB works with the workaround.)
