### ISSUE TITLE
Error when running or starting - missing package?

### ISSUE THREAD

**Issue by TheCakeGit** [robweber/xbmcbackup#202]
I get this error installing the addon, reinstalling the addon or Kodi makes no difference. Error also happens when starting Kodi or running the addon. Started happening after doing a restore. Using a Fire HD10 tablet. Am I missing a package?

Thx

![Screenshot_20210712-133548](https://user-images.githubusercontent.com/12487984/125289465-2a65ce00-e317-11eb-8b4a-adf32bb786f9.png)
![Screenshot_20210712-133744](https://user-images.githubusercontent.com/12487984/125289469-2afe6480-e317-11eb-8d63-0e042dadf03d.png)
![Screenshot_20210712-133602](https://user-images.githubusercontent.com/12487984/125289471-2b96fb00-e317-11eb-860a-fe0110dec2fc.png)
![Screenshot_20210712-133758](https://user-images.githubusercontent.com/12487984/125289472-2b96fb00-e317-11eb-819d-2088e85b0eb9.png)

**Comment by robweber** [comment]
Definitely an error, although not with this addon specifically. Looks like a lot of other dependencies are pulled in, one of them being the `script.module.chardet` addon. That appears to be where the error is originating from. What version of Kodi are you currently running? I want to wipe out my addons and try to download everything from the Kodi repo again. Could be something in that addon got updated and is now causing issues.

**Comment by TheCakeGit** [comment]
Sorry - 19.1 - thx

**Comment by robweber** [comment]
This was definitely an issue in an upstream library. Guessing Kodi didn't download it properly. On clean installs I've not had issues.
