### ISSUE TITLE
How to install beta channel?

### ISSUE THREAD

**Issue by vdurante** [robweber/xbmcbackup#205]
Hey! I am looking forward for the dropbox fix, but it has been unreleased since April. Is there a way of installing beta channel so I can enjoy the fix already? Thanks!

**Comment by robweber** [comment]
You can download the zip from the main GitHub page and install from the zip file in Kodi. Definitely my fault not getting that pushed sooner. Usually for fixes that are "show stoppers" I get them moved to the repo pretty quick but I lost sight of this one. Thanks for the reminder.

**Comment by vdurante** [comment]
@robweber thanks! It worked perfectly!
