### ISSUE TITLE
1.6.7: won't remember settings

### ISSUE THREAD

**Issue by jcollum** [robweber/xbmcbackup#206]
**Describe the problem**
When I change the settings and go back in to the settings to change something all of the settings have reverted to default 

**Platform and Kodi version**
Linux Mint 20.2, Kodi 19.3.0 

**Link to Debug Log**
I tried to upload the debug log but all I got on the paste site was "Something went wrong!". I see something in the logs about failed to load addon settings from special://profile/addon_data/script.xbmcbackup/settings.xml. Looks like it's expecting a directory that doesn't exist. I installed Kodi 19 fresh this morning.

**Comment by robweber** [comment]
If the directory can't be created this is an issue with Kodi itself and not the addon. The `special://profile/addon_data/` directory is managed by Kodi to store settings for all addons on the system. The `settings.xml` is created for each addon by Kodi and loaded through the UI to populate the settings.

**Comment by jcollum** [comment]
This is a fresh install of the current version of Kodi. I mean, I can post this to their issue tracker but if they changed how that directory works it seems like the bug lies with your program.

**Comment by robweber** [comment]
I see what you mean; although maybe I didn't explain this properly. When you alter or do anything with settings for addons - any addon - the saving and loading of the `settings.xml` file is handled directly by Kodi. That directory structure and files are all managed by the Kodi app and are transparent to the addon. On my end all I'm handed is a Python object that contains the settings. At no point do I load or write to those files, it's all handled by the core app. 

I suspect at the root of this is some kind of file permissions issue on your Kodi install. The underlying files in the `addon_data` directory haven't changed in years.

**Comment by jcollum** [comment]
OK thanks for the clarification.
