### ISSUE TITLE
🖐️Backup incompatible with kodi 20 Nexus

### ISSUE THREAD

**Issue by victore447** [robweber/xbmcbackup#214]
![155](https://user-images.githubusercontent.com/48101775/213180114-8cb07122-eb9a-4aa8-a445-1b7e6becf57f.gif) **Hello,**
 Kodi 20 Nexus is out .
👉 https://kodi.tv/download .

![kodi-20-nexus](https://user-images.githubusercontent.com/48101775/213180483-6bb1583b-7c6c-4e4c-b91c-1bbf11520817.jpg)

☝️ And your Backup extension is no longer compatible to restore a previously zipped file on it etc...

☝️ Nothing is displayed when selecting restore after after configuring the target path.

**Thank you for the answer✔️**

**Comment by robweber** [comment]
Good to know - thanks! I saw the RC candidates but they moved to release quicker than I expected. Hopefully the changes to the Python modules are minor.

**Comment by robweber** [comment]
Following up on this. I did a clean install of Nexus and then installed the most current version of Backup. I had no problem performing backups or restores. I did get a notification if the backup was taken on an old (Matrix) version of Kodi but you can click past that if you're sure you want to proceed. I'm going to mark this as "waiting for info" - I'll need a debug log from you to see what might be going on with your install specifically.

**Comment by victore447** [comment]
![143](https://user-images.githubusercontent.com/48101775/213288681-63fe0c26-3664-46aa-98ec-cc74811b6b2d.gif)On my side, this problem appeared during the migration from **Kodi 19.5 Matrix (not present on the Android tv play store)** to the kodi 20 Nexus.

![195](https://user-images.githubusercontent.com/48101775/213288768-2ffea298-8d69-4afd-b8f2-f6292ae81df8.gif)After posting my message above and to see the difference, I uninstalled kodi 20 then reinstalled the **kodi 19.3 which is present on the play store via Google play store Android tv.**

Then I again migrated to kodi 20 Nexus and there it works and I can see the desired zip file for restoration etc...![205](https://user-images.githubusercontent.com/48101775/213289048-804dd503-5878-4a03-bb39-d43b8111f33d.gif)

I add that now on kodi 20 with an expansion of storage via external hard drive of the tv box (I have an **Nvidia Shield Tv Android 11**, And **Strong Leap-S1 Android 10** ...),
![50](https://user-images.githubusercontent.com/48101775/213309125-c88aeb1f-ddc8-456c-99b4-a0e0ff1c6ffe.gif)with **nvidia shield tv Android 11** (plex server is integrated into it) backup only displays the target file if we have added a  source url smb (192.16.....) on kodi.
![273](https://user-images.githubusercontent.com/48101775/213309199-bbd4e110-3fcf-4b1c-b3a6-0d2d35183eec.gif)Otherwise it is not displayed by inserting the direct path "external storage etc.."

 So you can close the topic if you want or wait for another person to manifest for this bug ✔️

**Comment by victore447** [comment]
I add that now on kodi 20 with an expansion of storage via external hard drive of the tv box (I have an Nvidia Shield Tv, String Android tv...) 
![50](https://user-images.githubusercontent.com/48101775/213309125-c88aeb1f-ddc8-456c-99b4-a0e0ff1c6ffe.gif)backup only displays the target file if we have added a  source url smb (192.16.....) on kodi.

![273](https://user-images.githubusercontent.com/48101775/213309199-bbd4e110-3fcf-4b1c-b3a6-0d2d35183eec.gif)Otherwise it is not displayed by inserting the direct path "external storage etc.."✔️

**Comment by robweber** [comment]
I'll close this out for now. I think the issue can mainly be solved by adding specific entries for the sources you want to use. Kodi doesn't seem as adept at bringing in "auto discovered" external sources.
