### ISSUE TITLE
Cloud Storage Dropbox

### ISSUE THREAD

**Issue by eXim82** [robweber/xbmcbackup#215]
**Describe the problem**
I know its not really a bug, but since only Dropbox is supported now, I will post this. The problem is, when I set up Dropbox for the backup it works but only for 4 hours because Dropbox change something that the token now is only valid for 4 hours. So every 4 hours I have to make the activation process again. That's not really usable at the time like that. I know there is another post about Google drive. It would be really nice if Google drive will be supported or at least some workaround with the Dropbox method. Thank you in advance for this great plugin anyway. Please close this case if it's not useful for you.

**Platform and Kodi version**
Kodi 20

**Comment by robweber** [comment]
More testing to do on this but it looks like with a newer version of the Dropbox library there is support for refresh tokens. 

https://github.com/robweber/xbmcbackup/tree/dropbox_refresh_token
