### ISSUE TITLE
👋Failed Installations (Inpustream...)

### ISSUE THREAD

**Issue by victore447** [robweber/xbmcbackup#223]
![155](https://github.com/xbmc/xbmc/assets/48101775/128e6d55-2882-4532-b909-9dbfc94ed509)  **Hello,**
 It has been several months (with Kodi Nexus) that it is impossible to install Pvr Iptv simple client on another device (Android Box TV) when backing up via Backup & EzMaintenance+ addons. Even manually via Zip files.☝️This  does not work until several days later (+ 3 days).
![Pvr 20230623_190151](https://github.com/xbmc/xbmc/assets/48101775/9f61d97d-302f-422b-96ec-b7c8b8ec527e)

 ☝️**Once it worked when I changed my IP address via Vpn etc...And even now it doesn't change anything.**
![Pvr 20230623_190257](https://github.com/xbmc/xbmc/assets/48101775/82d9807d-3a8b-4da1-b824-e0d0de49564a)

 👆**The same is true for the Inputream Adaptive, Inputream.ffmpegdirect, Rtmp inputream etc. add-ons.**
![Inputream 20230623_180913](https://github.com/xbmc/xbmc/assets/48101775/f92b43d4-70d8-43c9-a425-3e80c167a327)

![46](https://user-images.githubusercontent.com/48101775/236531040-06b24a9a-6ac3-467d-b561-b1928058f1f2.gif)
👉 [kodi.log](https://github.com/xbmc/xbmc/files/11850974/kodi.log)

☝️About twenty Skins are configured there with video plugins like youtube, Dailymotion,🎞️ etc..
**Android Tv storage space shows Kodi is 5GB used** 

☝️ Even with a new Kodi weighing less than 300 MB this problem is there, Here are the logs of the new.
👉 [kodi.log](https://github.com/robweber/xbmcbackup/files/11856003/kodi.log)
👉 [kodi.old.log](https://github.com/robweber/xbmcbackup/files/11856004/kodi.old.log)

![674](https://github.com/robweber/xbmcbackup/assets/48101775/56830df2-e00b-4749-a14e-e8498f9d900c) **Backup even stops (closing kodi) during several backups during the maneuver at about 75%.**

 **Thank you for your answer** ✔️
[kodi.log](https://github.com/robweber/xbmcbackup/files/11856065/kodi.log)
[kodi.old.log](https://github.com/robweber/xbmcbackup/files/11856066/kodi.old.log)

**Comment by robweber** [comment]
Just to clarify you're trying to move files - via the Backup addon or similar - from one device to another? 

Looking at the logs you gave me there are several instances of `CAddonInstallJob[pvr.iptvsimple]: invalid package special://home/addons/packages/pvr.iptvsimple-20.10.1.zip` - this means there is something wrong with the addon package you are trying to install. 

It looks like one of these systems is a 32bit ARM system and the other is a 64bit. The IPTV addon is a binary addon and must be compiled specifically for different architecture types. It is not portable between different hardware platforms. Many addons are Python and can be ported between any system but some are binary and specific to certain platform types. You'll have to find  version that works on the platform you're migrating to.

**Comment by victore447** [comment]
![119](https://github.com/robweber/xbmcbackup/assets/48101775/4ffda1ba-05b7-4d19-b013-abfedc38f007)**Hello,**
 Yes I am trying to move files via Backup And Ez Maintenance+ addon from one device to another (Nvidia Shield TV 64bit to Box Leap-S1 Android tv 32bit).

 ☝️ **It works but then there are just the problems mentioned above and** 👆 **Only the Addons "Music visualization", Video player input stream (Inpustream Adaptive etc..)" & "Pvr iptv simple client" are refused  in moving and installing** (I have to wait several hours to three days to then be able to install them).

 ☝️Do you know of any addons that are Python and can be ported between any system?

 **Thank you for the answer**✔️

**Comment by robweber** [comment]
The PVR and Visualization addons for sure are binary so they wouldn't just copy over from one architecture type to the next. You're better off just excluding them and downloading from whatever repo they come from the proper binary for your system type. 

Most (like 90%) of Kodi addons are Python so they won't have any problems. A full list of official binary addons can be found in the [binary addons repo](https://github.com/xbmc/repo-binary-addons). You'll see this includes pvr, visualization, and inputstream addons. If you're getting addons from 3rd party repos you'll have to check those.

**Comment by victore447** [comment]
🖐️ **Hi,**
And how to install this binary Repo and or the files which are there on a traditional Kodi under Android via file manager etc..?

☝️Also there is nothing in the folder when I integrate👉 https://github.com/xbmc/repo-binary-addons via kodi file manager to download the repo..


 I just did a test, and Nexus Binary Zip installation fails with my blank Kodi Nexus build.
![46](https://github.com/robweber/xbmcbackup/assets/48101775/3270aa8e-2705-456e-954b-590e69af6d7a)
[kodi.log](https://github.com/robweber/xbmcbackup/files/11869406/kodi.log)

**Comment by robweber** [comment]
Sorry for the confusion - that link to the repo is the source code for everything. You can't import that into Kodi directly on it's own. I was just providing that as a reference to find any/all Kodi provided binary addons. 

Kodi comes shipped with the correct repo already installed for all the approved Kodi addons. You should just need to find it in the Addon manager and download it. All of the ones you've mentioned (Music Viz, Inpustream, PVR IPTV) are in there already.

**Comment by victore447** [comment]
🖐️ On Box Shield TV 64 bits I recreated a new Kodi backup without Pvr iptv simple client (uninstall) with some addons from the Kodi repository (Youtube, Vimeo etc..).

 Then on the other 32 Bit Box tv device I did a restore.

 ☝️After manually downloading this official Kodi Pvr iptv simple client zip👉 https://github.com/kodi-pvr/pvr.iptvsimple/tree/Nexus to install it  **Still the same problem (installation failure)**

 ☝️ In fact there is no other solution than to wait a few hours to a few days to be able to install Pvr iptv simple clients, Inpustream Adaptive etc... as indicated above ✔️


👉  [kodi.old.log](https://github.com/robweber/xbmcbackup/files/11872450/kodi.old.log)
👉  [kodi.log](https://github.com/robweber/xbmcbackup/files/11872451/kodi.log)

**Comment by robweber** [comment]
Sorry you're having issues with this but downloading the source files from the addon repo will not work. For Python addons that works fine but for binary addons they must be __compiled__ for your specific architecture first. I checked on my system and a default install of Kodi with no modifications can simply download the IPTV addon from the addon browser as long as you're on the internet. You shouldn't have to do any more than that to get it working.

**Comment by victore447** [comment]
Well enlighten me so that we stop there and close the issue, There is no other solution than to wait a few hours to a few days to be able to install Pvr iptv simple clients, Inpustream Adaptive etc... like  shown above ✔️
