### ISSUE TITLE
Scripting Restore

### ISSUE THREAD

**Issue by MrC001** [robweber/xbmcbackup#225]
{ "jsonrpc": "2.0", "method": "Addons.ExecuteAddon","params":{"addonid":"script.xbmcbackup","params":{"mode":"restore","archive":"000000000000","sets":"config|database"}}, "id": 1 }

In the above, what is the correct format for the archive, using something like -- 202308301408 -- does not work or adding the .zip
or the full URL.  All works fine just launching as restore and selecting the update.  Searched everywhere I can not find an answer.

Backups are on my server and saving and restore works with file selection.

**Comment by robweber** [comment]
Do you have any logs of when this is happening? Just now I used the below JSON to kick-start a restore on my test system. It worked as expected. For zip files you do have to add the `.zip` extension but otherwise just the archive folder name is working for me. 

```
{ "jsonrpc": "2.0", "method": "Addons.ExecuteAddon","params":{"addonid":"script.xbmcbackup","params":{"mode":"restore","archive":"202308311446.zip","sets":"config|database"}}, "id": 1 }

```

**Comment by MrC001** [comment]
I never tried with .zip ... I will try today.

**Comment by robweber** [comment]
Sounds good. To be clear I had it work with both (zip files and folders). For folders you just need the folder name and for zip files you have to add .zip.

**Comment by MrC001** [comment]
Yep, worked fine after adding .zip
Thank you !! My 77 yr old Dad thanks you.  Now easy to fix his setup without spending 6 hours on the phone.
All I need to figure out now (not the best coder out there) is to wait until restore complete and reboot.

**Comment by robweber** [comment]
Glad that worked. There is a JSON call that can do that as well if you're triggering stuff that way - https://kodi.wiki/view/JSON-RPC_API/v13#System.Reboot
