### ISSUE TITLE
ENHANCEMENT REQUEST

### ISSUE THREAD

**Issue by daherlihy** [robweber/xbmcbackup#228]
**Problem** - When I do a restore that contains config files (for instance the sources.xml, advancedsettings.xml, keymap.xml, etc.), they are not updated immediately in Kodi until I restart it. 

Many don't realise this and think the restore feature doesn't work - myself included until I asked [Reddit](https://www.reddit.com/r/kodi/comments/19doxcq/how_do_i_back_up_sources/.

**Suggestion/Solution** - if/when users restore config files (at the very least), there should be a prompt to advise restarting Kodi so as to see the reflected changes from the restoration.

**Comment by robweber** [comment]
Good point. When an `advancesettings` file is detected in the restore point there user is prompted to restore and restart; however this is not fool proof. There are edge cases where this might not be detected. Checking the modified date for these files post-restore is probably a better method of determining if they've been touched.

**Comment by daherlihy** [comment]
Thanks for looking into this. I'll leave it up to you to decide whatever is best - I'm just glad I know and want to share the knowledge for anyone else who doesn't know :)

**Comment by robweber** [comment]
I ended up adding a global prompt at the end of all restore jobs to recommend Kodi is restarted. Keeping track of all the files that may require a restart is way too work intensive. Easier to just clean reboot the whole system no matter what.

**Comment by daherlihy** [comment]
Yep makes perfect sense, thanks again for the update and for looking into this!
