### ISSUE TITLE
Doesn't work on Kodi 21

### ISSUE THREAD

**Issue by Elvitek** [robweber/xbmcbackup#229]
I created a backup from Kodi 20 on the Xbox Series S and wanted to import it to Kodi 21 on the Xbox Series X but it doesn't work. When will the addon be updated? Thank you.

**Platform and Kodi version**

Kodi 21.0-RC1 (20.90.900) on Xbox Series X (retail mode, not uwp or dev)

**Comment by robweber** [comment]
I'll have to get a release candidate installed and test it out. Could be some changes in the python API. I generally keep things working on the latest stable release so haven't jumped into the Omega releases yet. Will keep this open for further testing.

**Comment by Elvitek** [comment]
Hopefully soon, thanks.

**Comment by Elvitek** [comment]
Now it works by enabling the addons and repositories again, thanks!
