### ISSUE TITLE
I can't restore a simple backup

### ISSUE THREAD

**Issue by an0nimo** [robweber/xbmcbackup#236]
Hi.
Below is the log lines of the error on KODI 20.2, Android 10 rooted with Magisk on my TV Box.
I did the backup but after using the option RESTORE is shown the error message saying to see the log file.
The BACKUP folder is in SD card but I think that is not the problema because I never had that issue before and the backup file is generate with no error in this BACKUP folder in the SD card.
When the BACKUP folder is empty so is openning a empty small window too like the image on the end.
The backup addons version is 1.7.0.

`2024-04-29 23:24:08.234 T:9677    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ValueError'>
                                                   Error Contents: invalid literal for int() with base 10: ''
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/default.py", line 107, in <module>
                                                       restorePoints = backup.listBackups()
                                                                       ^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/resources/lib/backup.py", line 88, in listBackups
                                                       folderName = self._dateFormat(aDir)
                                                                    ^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/resources/lib/backup.py", line 471, in _dateFormat
                                                       date_time = datetime(int(dirName[0:4]), int(dirName[4:6]), int(dirName[6:8]), int(dirName[8:10]), int(dirName[10:12]))
                                                                                                                                     ^^^^^^^^^^^^^^^^^^
                                                   ValueError: invalid literal for int() with base 10: ''
                                                   -->End of Python script error report<--`
![Sem título-3](https://github.com/robweber/xbmcbackup/assets/52868596/e43daab7-f688-47f1-a241-1f8e1a282ba1)

**Comment by robweber** [comment]
It's like it's not parsing the name of the folder correctly. Are there other folders in the backup directory? The Backup addon should be the only thing writing to whatever directory you've chosen - especially if using the retention options. Can you do a screenshot or file listing of the files in that folder?

**Comment by an0nimo** [comment]
Thanks for the quick response.
There are no other folders in the BACKUP directory.
Previously the path was sd card/KODI/BACKUP.
To test, I changed it to 0/BACKUP, that is, the BACKUP folder is in the root of the internal memory, without subfolders or files.
I made the normal backup to the 0/BACKUP folder but immediately after, trying to use the RESTORE function the error message appears.
Today I did a test again and the backup file was shown when I choose RESTORE option.
Maybe some addon file was not read correctly by KODI yesterday and that issue began to appear.
It is normal now.
Thank you.

**Comment by robweber** [comment]
Weird. On an SD card I wouldn't rule out some kind of hidden directory or file but in either case you got it working. I'll close this out.

**Comment by an0nimo** [comment]
Many computer technicians claim that many problems are resolved only restarting the machine. 
I forgot to do this before posting the problem here.
Sorry.
![image](https://github.com/robweber/xbmcbackup/assets/52868596/8a62b160-71ad-444c-b81d-b2ca7fdac6ef)
