### ISSUE TITLE
Can't restore from a zipped backup file

### ISSUE THREAD

**Issue by RayzaEFC** [robweber/xbmcbackup#240]
Backup app can't restore a zipped backup file anymore. This used to work but for some reason it doesn't now. When you try it says Backup error, check log for more information. This helps a lot with speed so would be great if sorted. Thanks

**Comment by utdrmac** [comment]
Same here. I just bought a rpi4 and trying to migrate from my older rpi3. I took a backup using this addon on the old pi, copied it to this new pi, and it won't work. Where exactly is the log located?

**Comment by RayzaEFC** [comment]
> Same here. I just bought a rpi4 and trying to migrate from my older rpi3. I took a backup using this addon on the old pi, copied it to this new pi, and it won't work. Where exactly is the log located?

Not sure about raspberry pi but Android it's in the Data folder, Windows it's in the roaming folder

**Comment by robweber** [comment]
Have you tried using the version from this repo or just the one available in Kodi? There was a [similar issue](https://github.com/robweber/xbmcbackup/issues/235) and a [fix for it](https://github.com/robweber/xbmcbackup/commit/324f3a46cf8d9a1d49ea3c1d3da06a9fa9ee50bc) not too long ago.

**Comment by utdrmac** [comment]
> Have you tried using the version from this repo or just the one available in Kodi?

I'm using the one from Kodi. I searched for it on the repos and installed it. The version from Kodi is different? How come? How do I install a newer version?

**Comment by RayzaEFC** [comment]
> Have you tried using the version from this repo or just the one available in Kodi? There was a [similar issue](https://github.com/robweber/xbmcbackup/issues/235) and a [fix for it](https://github.com/robweber/xbmcbackup/commit/324f3a46cf8d9a1d49ea3c1d3da06a9fa9ee50bc) not too long ago.

Sorry not the best at all this, how do I get the repo, do I install it from a zip file on Kodi, if so what's the address

**Comment by RayzaEFC** [comment]
> Have you tried using the version from this repo or just the one available in Kodi? There was a [similar issue](https://github.com/robweber/xbmcbackup/issues/235) and a [fix for it](https://github.com/robweber/xbmcbackup/commit/324f3a46cf8d9a1d49ea3c1d3da06a9fa9ee50bc) not too long ago.

I've managed to manually download the zip file and install on Kodi. Is there a web address that can be entered in File Manager on Kodi so I can get the repo from there? Thanks

**Comment by robweber** [comment]
I don't have a separate repo setup just for this addon. Generally the one in the Kodi repo is the latest one. I try to space out doing updates as the Kodi team has a lot of addons to go through and try and get merged in. This error was found right after a recent update. I plan to get this fix pushed up there soon.

**Comment by RayzaEFC** [comment]
> I don't have a separate repo setup just for this addon. Generally the one in the Kodi repo is the latest one. I try to space out doing updates as the Kodi team has a lot of addons to go through and try and get merged in. This error was found right after a recent update. I plan to get this fix pushed up there soon.

Ok great and thanks for reply and thanks for creating the app too

**Comment by daherlihy** [comment]
Having the same issue here - restoring compressed backups doesn't work, but as a workaround there's no issue restoring non-compressed backups.

Great to hear that a fix is being pushed soon too :)

**Comment by mephitrpg** [comment]
Please, release the fix, so the Kodi on my TV can update it

**Comment by daherlihy** [comment]
> Please, release the fix, so the Kodi on my TV can update it

As a workaround, I'm pretty sure that if you extract the ZIP file into a folder of the same name (might already exist inside the ZIP file), you'll be able to restore the contents of your backup uncompressed

**Comment by robweber** [comment]
PR: https://github.com/xbmc/repo-scripts/pull/2640

Sorry for the delay - been a busy summer.
