### ISSUE TITLE
zip backups get larger every backup

### ISSUE THREAD

**Issue by prometheanfire** [robweber/xbmcbackup#61]
if I delete some backups it gets smaller again (deleted around the new year you can see).

    -rwxr--r--. 1 username users  23G Dec 22 06:35 201412220500.zip
    -rwxr--r--. 1 username users  27G Dec 29 06:44 201412290500.zip
    -rwxr--r--. 1 username users  25K Jan  5 05:00 201501050500.zip
    -rwxr--r--. 1 username users 3.8G Jan 12 05:16 201501120500.zip
    -rwxr--r--. 1 username users 7.5G Jan 19 05:32 201501190500.zip
    -rwxr--r--. 1 username users  12G Jan 26 05:51 201501260500.zip

**Comment by robweber** [comment]
that is really interesting. What size do you feel is correct, the larger or the smaller? Obviously 25K is way off but are all your files large enough for 20+GB or are you more in the 3-7 range? It could be that the addon is failing to move some files for some reason, hard to say. Debug log if you would.

**Comment by prometheanfire** [comment]
The 25k file only has a few xml files.

201501120500 was correct in size and what it extracted.

201501190500 asked me to overwrite some stuff, like it was extracting the same stuff twice. the following are a couple of duplicates.

    201501190500/addons/metadata.albums.allmusic.com/resources/language/French/strings.xml
    201501190500/addons/metadata.albums.allmusic.com/resources/language/Dutch/strings.xml

Those were also the first backed up items (after 201501190500/xbmcbackup.val , but that may have been because alphabetical ordering or something).


I greped a listing of the bad backup and here's what I found.

    grep metadata.albums.allmusic.com 201501190500.filelist
          223  01-19-2015 05:00   201501190500/addons/metadata.albums.allmusic.com/resources/language/French/strings.xml
          207  01-19-2015 05:00   201501190500/addons/metadata.albums.allmusic.com/resources/language/Dutch/strings.xml
          257  01-19-2015 05:00   201501190500/addons/metadata.albums.allmusic.com/resources/language/Russian/strings.xml
          217  01-19-2015 05:00   201501190500/addons/metadata.albums.allmusic.com/resources/language/Portuguese/strings.xml
          189  01-19-2015 05:00   201501190500/addons/metadata.albums.allmusic.com/resources/language/German/strings.xml
          203  01-19-2015 05:00   201501190500/addons/metadata.albums.allmusic.com/resources/language/Polish/strings.xml
          387  01-19-2015 05:00   201501190500/addons/metadata.albums.allmusic.com/resources/language/Swedish/strings.xml
          223  01-19-2015 05:00   201501190500/addons/metadata.albums.allmusic.com/resources/language/Hungarian/strings.xml
          191  01-19-2015 05:00   201501190500/addons/metadata.albums.allmusic.com/resources/language/English/strings.xml
          190  01-19-2015 05:00   201501190500/addons/metadata.albums.allmusic.com/resources/language/Chinese (Simple)/strings.xml
          213  01-19-2015 05:00   201501190500/addons/metadata.albums.allmusic.com/resources/language/Korean/strings.xml
          216  01-19-2015 05:00   201501190500/addons/metadata.albums.allmusic.com/resources/language/Finnish/strings.xml
          235  01-19-2015 05:00   201501190500/addons/metadata.albums.allmusic.com/resources/language/Bulgarian/strings.xml
          191  01-19-2015 05:00   201501190500/addons/metadata.albums.allmusic.com/resources/language/Spanish/strings.xml
          222  01-19-2015 05:00   201501190500/addons/metadata.albums.allmusic.com/resources/settings.xml
         4995  01-19-2015 05:00   201501190500/addons/metadata.albums.allmusic.com/allmusic.xml
        12584  01-19-2015 05:00   201501190500/addons/metadata.albums.allmusic.com/icon.png
        15202  01-19-2015 05:00   201501190500/addons/metadata.albums.allmusic.com/addon.xml
        28832  01-19-2015 05:00   201501190500/addons/packages/metadata.albums.allmusic.com-2.1.0.zip
          223  01-19-2015 05:07   201501190500/addons/metadata.albums.allmusic.com/resources/language/French/strings.xml
          207  01-19-2015 05:07   201501190500/addons/metadata.albums.allmusic.com/resources/language/Dutch/strings.xml
          257  01-19-2015 05:07   201501190500/addons/metadata.albums.allmusic.com/resources/language/Russian/strings.xml
          217  01-19-2015 05:07   201501190500/addons/metadata.albums.allmusic.com/resources/language/Portuguese/strings.xml
          189  01-19-2015 05:07   201501190500/addons/metadata.albums.allmusic.com/resources/language/German/strings.xml
          203  01-19-2015 05:07   201501190500/addons/metadata.albums.allmusic.com/resources/language/Polish/strings.xml
          387  01-19-2015 05:07   201501190500/addons/metadata.albums.allmusic.com/resources/language/Swedish/strings.xml
          223  01-19-2015 05:07   201501190500/addons/metadata.albums.allmusic.com/resources/language/Hungarian/strings.xml
          191  01-19-2015 05:07   201501190500/addons/metadata.albums.allmusic.com/resources/language/English/strings.xml
          190  01-19-2015 05:07   201501190500/addons/metadata.albums.allmusic.com/resources/language/Chinese (Simple)/strings.xml
          213  01-19-2015 05:07   201501190500/addons/metadata.albums.allmusic.com/resources/language/Korean/strings.xml
          216  01-19-2015 05:07   201501190500/addons/metadata.albums.allmusic.com/resources/language/Finnish/strings.xml
          235  01-19-2015 05:07   201501190500/addons/metadata.albums.allmusic.com/resources/language/Bulgarian/strings.xml
          191  01-19-2015 05:07   201501190500/addons/metadata.albums.allmusic.com/resources/language/Spanish/strings.xml
          222  01-19-2015 05:07   201501190500/addons/metadata.albums.allmusic.com/resources/settings.xml
         4995  01-19-2015 05:07   201501190500/addons/metadata.albums.allmusic.com/allmusic.xml
        12584  01-19-2015 05:07   201501190500/addons/metadata.albums.allmusic.com/icon.png
        15202  01-19-2015 05:07   201501190500/addons/metadata.albums.allmusic.com/addon.xml
        28832  01-19-2015 05:07   201501190500/addons/packages/metadata.albums.allmusic.com-2.1.0.zip

**Comment by prometheanfire** [comment]
so it's backing up multiple times, odd :(

**Comment by robweber** [comment]
It almost seems like it's rea-dding the files from the packages/ directory (all zip files) and since they are zip files themselves extracting them into the zip to appear as duplicate files. The odd thing is that it should ignore these types of files to begin with. Perhaps this is not working? I am doing more testing here.

**Comment by robweber** [comment]
I just added an error if the old zip archive can't be deleted. I've seen this happen in a few cases now and it seems like then files are being added to the archive multiple times as it's combing the old and new versions into one archive. This warning will exit the program as this is a non-recoverable error, but not much else can be done if we can't continue. 

https://github.com/robweber/xbmcbackup/commit/49f6b176e8b12c1c2ff0bb99193dcb4a4f625695

**Comment by prometheanfire** [comment]
Thanks, I've also switched to a locally mounted cifs dir as well, dunno if that will help (instead of using samba directly).  I'm guessing it might, have a feeling there might be some timeout (some backups didn't grow recently...).

**Comment by prometheanfire** [comment]
rebooting 'fixes' it.  I switched to a faster network (replaced access point) and it doesn't seem to help.

**Comment by robweber** [comment]
Didn't forget about this. I'm waiting for some stuff to update in the Kodi repo and then will push a new version of the addon. If nothing else the new version will have more helpful error messages.

**Comment by NHellFire** [comment]
I'm having the same problem on my pi. My ~/.kodi is 3.4GB, but it created a 7GB zip (filling my SD card).

**Comment by brokeh** [comment]
This is also a problem for non-zip backups, it is just that it writes the same file multiple times. Check out my PR for the fix.

**Comment by robweber** [comment]
This was merged in and now pushed to the Kodi repo as version 1.0.5. Any confirmation this cleared things up?

**Comment by prometheanfire** [comment]
ya, I tested the change when it went in originally.
