### ISSUE TITLE
Backup fails, leaves zip file in temp

### ISSUE THREAD

**Issue by cffm** [robweber/xbmcbackup#62]
So this was running fine for the past, no idea, since I have it. No issues whatsoever. I keep a 7 day roll and 1/31 was the last successful backup. It leaves xbmc_backup_temp.zip in the temp file (by the way, it is now kodi ;) and that's it. No error message, it just fails.

The ZIP file seems to be broken (cannot open it using windows, I have to use 7zip). It only contains 2 folders and is 250 MB. Normale backup for me is 650 MB so it crashes during creation (I am guessing). That it fails on 2/1 (new month shock?) could be a coincidence. Looking thru my 7 day windows, it did sort of failed a few days before (size of ZIP was 160 MB vs 650 normale range) but the ZIP made it to storage. Manual or scheduled right now does nothing besides leave a ZIP in the temp folder...

Comparing what is in a working ZIP vs broken, it seems to crash backing up uderdata folder. The saltscache file did not make it.

**Comment by robweber** [comment]
Can you check and make sure there is enough space on the drive? That would be a common reason for the zip file to fail as it stages everything on the local drive, would also hose up the archive I imagine. If that isn't the case can you post back a debug log? Maybe there is some error messages there. 

I'll get around to naming all the files to "kodi" eventually, this one was kind of "under the hood" so didn't think anyone would notice!

**Comment by cffm** [comment]
Did you do some remote magic shenanigans? This hasn't worked since 1/31. Manual one either failed or crashed OpenElec. I enabled logging and it did crash it again. Wanted to try again and it worked. Working now ever since. Magic could have been, enable debug and crash it - boom... fixed... ;)

Thank you for looking into it!

**Comment by robweber** [comment]
Glad it's working, weird as I didn't do anything!
