### ISSUE TITLE
can't write to upnp server

### ISSUE THREAD

**Issue by cqst** [robweber/xbmcbackup#76]
Hi

I can backup on local filesystem but I can't manage to backup on upnp devices which are writeable btw.

I get this error message on GUI :

"The destination may not be writable
Zip archive could not be copied"

Here is extract of log file : 

00:57:06 T:123145304526848  NOTICE: script.xbmcbackup-1.0.6: Source: /Users/ben/.kodi/temp/
00:57:06 T:123145304526848   DEBUG: script.xbmcbackup-1.0.6: Writing file: /Users/ben/.kodi/temp/201511010056.zip
00:57:06 T:123145304526848    INFO: Platinum [neptune.threads.posix]: NPT_PosixThread::NPT_PosixThread
00:57:06 T:123145303453696    INFO: Platinum [neptune.http]: requesting URL http://192.168.0.254:52424/service/ContentDirectory/control
00:57:06 T:123145303453696    INFO: Platinum [neptune.http]: calling connector (proxy:no) (http 1.1:yes) (url:http://192.168.0.254:52424/service/ContentDirectory/control)
00:57:06 T:123145303453696    INFO: Platinum [neptune.tls]: looking for a connection to reuse
00:57:06 T:123145303453696    INFO: Platinum [neptune.tls]: TLS connector will connect to 192.168.0.254:52424
00:57:06 T:123145303453696    INFO: Platinum [neptune.http]: got connection (reused: false)
00:57:06 T:123145303453696    INFO: Platinum [neptune.http]: sending body stream, 973 bytes
00:57:06 T:123145303453696    INFO: Platinum [platinum.media.server.didl]: Parsing Didl...
00:57:06 T:123145304526848   ERROR: CUPnPDirectory::GetResource - no items returned for object 0/1/sandisk 64go/201511010056.zip

Made the test from kodi 15.2 on mac and then same on kodi installed on android tv, both can't handle to write backup file on upnp server.

Am I doing something wrong ? known issue ? do you need more details ?

Thx for the job btw ;)

**Comment by robweber** [comment]
Seems like an issue with the Kodi UPNP implementation. The error message is coming from the Kodi filesystem handler. The error message doesn't make a whole lot of sense to me. One thing to try would be to add the UPNP server as a source and then use the file manager to try and copy a file over to it. Will that work from within Kodi?

**Comment by cqst** [comment]
I can add source in "system" > "file manager" to the upnp directory that i want to write to

but then it's not listed in "backup" browse directory

**Comment by robweber** [comment]
When you add it as a source can you then copy a file to it using the Kodi File Manager? I'm just trying to see if writing to UPNP devices is supported in Kodi at all.

**Comment by cqst** [comment]
ok sorry I misunderstood (french here ;))

i can't copy that way. no "copy" in context menu after selecting a file in this case...
Tried with 2 local file system and "copy" appeared

so I guess you are right and it's about Kodi implementation ?

**Comment by robweber** [comment]
I would have to say that's it based on the testing. I'll mark this as closed.

**Comment by cqst** [comment]
ok 

fyi I opened a ticket on kodi : http://trac.kodi.tv/ticket/16362
