### ISSUE TITLE
EXCEPTION: Unknown exception thrown from the call "read"

### ISSUE THREAD

**Issue by der-htc** [robweber/xbmcbackup#77]
Today I got this error while trying to make a backup.
(Kodi 15.2 with OpenELEC 6.0.0 on Wetek Play.)

20:17:22 T:2424013888  NOTICE: -->Python Interpreter Initialized<--
20:17:24 T:2424013888  NOTICE: script.xbmcbackup-1.0.6: Starte
20:17:24 T:2424013888  NOTICE: script.xbmcbackup-1.0.6: Lokales Verzeichnis: /storage/.kodi/
20:17:24 T:2424013888  NOTICE: script.xbmcbackup-1.0.6: Entferntes Verzeichnis: 201511112017/
20:17:24 T:2424013888  NOTICE: script.xbmcbackup-1.0.6: Modus - Sichern
20:17:24 T:2424013888  NOTICE: script.xbmcbackup-1.0.6: Dateiliste wird erzeugt
20:17:29 T:2424013888  NOTICE: script.xbmcbackup-1.0.6: Writing files to: 201511112017/
20:17:29 T:2424013888  NOTICE: script.xbmcbackup-1.0.6: Source: /storage/.kodi/
20:29:27 T:2424013888   ERROR: EXCEPTION: Unknown exception thrown from the call "read"
20:29:27 T:2424013888   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: Unknown exception thrown from the call "read"
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.xbmcbackup/default.py", line 73, in <module>
                                                backup.run(mode)
                                              File "/storage/.kodi/addons/script.xbmcbackup/resources/lib/backup.py", line 256, in run
                                                filesCopied = self.backupFiles(fileGroup['files'],self.xbmc_vfs,self.remote_vfs)
                                              File "/storage/.kodi/addons/script.xbmcbackup/resources/lib/backup.py", line 482, in backupFiles
                                                wroteFile = dest.put(aFile,dest.root_path + aFile[len(source.root_path):])
                                              File "/storage/.kodi/addons/script.xbmcbackup/resources/lib/vfs.py", line 97, in put
                                                self.zip.writestr(utils.encode(dest),aFile.read())
                                            RuntimeError: Unknown exception thrown from the call "read"
                                            -->End of Python script error report<--

**Comment by cffm** [comment]
Same here. Started with OE 6.0 (Kodi 15.2). Doesn't go thru...

**Comment by Grossdm** [comment]
I have been struggling with this same error!  The temp zip file is in the temp folder, but the script fails with an error.  I'm running Jarvis RC1 on a Minix Android box.

**Comment by robweber** [comment]
I can't find the PR offhand but I believe there was an issue using cached results when checking for files in the Kodi python libraries. Was fixed within the last year. Wish I had more info but I believe that is what is happening here.
