### ISSUE TITLE
Backup to google drive from 'script.xbmcbackup'

### ISSUE THREAD

**Issue by scareyman** [robweber/xbmcbackup#79]
Hello,

I'm running the most up to date kodi on an amazon tv stick.

The problem I have is backing up to gdrive. I have followed the instructions precisely and it appears to be generating the zip file for backup transfer when it suddenly crashes kodi.

Log file details below (user specific details redacted from the copy and paste)

I only got as far as noticing the call to 'none type' but I'm not sure how to proceed with that or if that's the right place to start.

13:09:12 T:1663920824  NOTICE: Thread TCPServer start, auto delete: false
13:09:12 T:1656046728  NOTICE: -->Python Interpreter Initialized<--
13:09:12 T:1659040480  NOTICE: Previous line repeats 2 times.
13:09:12 T:1659040480  NOTICE: Thread JobWorker start, auto delete: true
13:09:12 T:1681990088  NOTICE: Thread LanguageInvoker start, auto delete: false
13:09:13 T:1651304200  NOTICE: -->Python Interpreter Initialized<--
13:09:13 T:1651303128  NOTICE: Previous line repeats 1 times.
13:09:13 T:1651303128  NOTICE: script.grab.fanart: Grab Fanart Service Started
13:09:15 T:1658838120  NOTICE:  StorageServer Module loaded RUN
13:09:15 T:1658838120  NOTICE: StorageClient-2.5.4 Starting server
13:09:18 T:1661864744  NOTICE: -->Python Interpreter Initialized<--
13:09:19 T:1713042312  NOTICE: Previous line repeats 1 times.
13:09:19 T:1713042312  NOTICE: Thread BackgroundLoader start, auto delete: false
13:09:19 T:1711891248  NOTICE: Thread JobWorker start, auto delete: true
13:09:23 T:1712952720  NOTICE: Thread LanguageInvoker start, auto delete: false
13:09:23 T:1712952720  NOTICE: -->Python Interpreter Initialized<--
13:09:29 T:1712952720   ERROR: WARNING:root:[Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/']
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.googleapi/lib/apiclient/discovery_cache/**init**.py", line 38, in autodetect
                                                from . import file_cache
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.googleapi/lib/apiclient/discovery_cache/file_cache.py", line 132, in <module>
                                                cache = Cache(max_age=DISCOVERY_DOC_MAX_AGE)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.googleapi/lib/apiclient/discovery_cache/file_cache.py", line 78, in **init**
                                                self._file = os.path.join(tempfile.gettempdir(), FILENAME)
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/tempfile.py", line 254, in gettempdir
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/tempfile.py", line 201, in _get_default_tempdir
                                            IOError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/']
13:09:29 T:1712952720  NOTICE: .
13:09:31 T:1712952720  NOTICE: GoogleDriveFile({u'mimeType': u'application/vnd.google-apps.folder', u'version': u'78097', u'appDataContents': False, u'labels': {u'restricted': False, u'starred': False, u'viewed': True, u'hidden': False, u'trashed': False}, u'explicitlyTrashed': False, u'etag': u'"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"', u'lastModifyingUserName': u'XXXXXXXX', u'writersCanShare': True, u'owners': [{u'emailAddress': u'XXXXXXXXXXXXXXXX', u'kind': u'drive#user', u'isAuthenticatedUser': True, u'displayName': u'XXXXXXXXXXXX', u'permissionId': u'XXXXXXXXXXXXXXXX'}], u'id': u'XXXXXXXXXXXXXXXX', u'lastModifyingUser': {u'emailAddress': u'XXXXXXXXXXXXXXXXXXXXXXXX', u'kind': u'drive#user', u'isAuthenticatedUser': True, u'displayName': u'Stephen Carey', u'permissionId': u'XXXXXXXXXXXXXXXXXXXXX'}, u'copyable': False, u'ownerNames': [u'Stephen Carey'], u'lastViewedByMeDate': u'2015-12-24T13:08:25.760Z', u'parents': [{u'isRoot': True, u'kind': u'drive#parentReference', u'id': u'XXXXXXXXXXXXXXXXX', u'selfLink': u'https://XXXXXXXXXXXXXXXXXXXXX', u'parentLink': u'https://www.XXXXXXXXXXXXXXXX'}], u'shared': False, u'editable': True, u'markedViewedByMeDate': u'1970-01-01T00:00:00.000Z', u'modifiedDate': u'2015-12-24T12:54:39.499Z', u'createdDate': u'2015-12-24T12:54:39.499Z', u'iconLink': u'https://ssl.gstatic.com/docs/doclist/images/icon_11_collection_list_1.png', u'kind': u'drive#file', u'alternateLink': u'https://XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', u'title': u'Kodi Backup', u'modifiedByMeDate': u'2015-12-24T12:54:39.499Z', u'userPermission': {u'kind': u'drive#permission', u'etag': u'"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"', u'role': u'owner', u'type': u'user', u'id': u'me', u'selfLink': u'https://www.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'}, u'spaces': [u'drive'], u'quotaBytesUsed': u'0', u'selfLink': u'https://www.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'})
13:09:31 T:1712952720  NOTICE: script.xbmcbackup-1.0.6: Starting
13:10:54 T:1718633720  NOTICE: Thread LanguageInvoker start, auto delete: false
13:10:54 T:1718633720  NOTICE: -->Python Interpreter Initialized<--
13:10:59 T:1718633720   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: attribute of type 'NoneType' is not callable
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/default.py", line 37, in <module>
                                                backup = XbmcBackup()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/resources/lib/backup.py", line 46, in __init__
                                                self.configureRemote()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/resources/lib/backup.py", line 62, in configureRemote
                                                self.remote_vfs = GoogleDriveFilesystem('/Kodi Backup/')
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/resources/lib/vfs.py", line 292, in **init**
                                                self.setup()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/resources/lib/vfs.py", line 312, in setup
                                                gauth.LoadCredentialsFile(xbmc.validatePath(xbmc.translatePath(utils.data_dir() + 'google_drive.dat')))
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/resources/lib/pydrive/auth.py", line 236, in LoadCredentialsFile
                                                self.credentials = storage.get()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.oauth2client/lib/oauth2client/client.py", line 372, in get
                                                return self.locked_get()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.oauth2client/lib/oauth2client/file.py", line 79, in locked_get
                                                credentials = Credentials.new_from_json(content)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.oauth2client/lib/oauth2client/client.py", line 290, in new_from_json
                                                return from_json(s)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.oauth2client/lib/oauth2client/client.py", line 622, in from_json
                                                data['token_expiry'], EXPIRY_FORMAT)
                                            TypeError: attribute of type 'NoneType' is not callable
                                            -->End of Python script error report<--
13:14:06 T:1568347816  NOTICE: GL_VENDOR = Broadcom
13:14:06 T:1568347816  NOTICE: GL_RENDERER = VideoCore IV HW
13:14:06 T:1568347816  NOTICE: GL_VERSION = OpenGL ES 2.0
13:14:06 T:1568347816  NOTICE: GL_SHADING_LANGUAGE_VERSION = OpenGL ES GLSL ES 1.00
13:14:06 T:1568347816  NOTICE: GL_EXTENSIONS = GL_OES_compressed_ETC1_RGB8_texture GL_OES_compressed_paletted_texture GL_OES_texture_npot GL_OES_depth24 GL_OES_vertex_half_float GL_OES_EGL_image GL_OES_EGL_image_external GL_EXT_discard_framebuffer GL_OES_rgb8_rgba8 GL_OES_depth32 GL_OES_packed_depth_stencil GL_EXT_texture_format_BGRA8888 GL_EXT_debug_marker

**Comment by scareyman** [comment]
here's the first half of the log file in case it's relevant.

13:09:08 T:1568347816  NOTICE: special://profile/ is mapped to: special://masterprofile/
13:09:08 T:1568347816  NOTICE: -----------------------------------------------------------------------
13:09:08 T:1568347816  NOTICE: Starting Kodi (15.2 Git:2015-10-27-17fa8da). Platform: Android ARM 32-bit
13:09:08 T:1568347816  NOTICE: Using Release Kodi x32 build
13:09:08 T:1568347816  NOTICE: Kodi compiled Oct 27 2015 by GCC 4.8.0 for Android ARM 32-bit API level 17 (API level 17)
13:09:08 T:1568347816  NOTICE: Running on Amazon AFTM with Android 4.2.2 API level 17, kernel: Linux ARM 32-bit version 3.0.31+
13:09:08 T:1568347816  NOTICE: FFmpeg version: 2.6.4-kodi-2.6.4-Isengard
13:09:08 T:1568347816  NOTICE: Host CPU: ARMv7 Processor rev 0 (v7l), 2 cores available
13:09:08 T:1568347816  NOTICE: Product: montoya, Device: montoya, Board: capri - Manufacturer: Amazon, Brand: BRCM, Model: AFTM, Hardware: montoya
13:09:08 T:1568347816  NOTICE: External storage path = /storage/emulated/0; status = ok
13:09:08 T:1568347816  NOTICE: ARM Features: Neon enabled
13:09:08 T:1568347816  NOTICE: special://xbmc/ is mapped to: /data/data/org.xbmc.kodi/cache/apk/assets
13:09:08 T:1568347816  NOTICE: special://xbmcbin/ is mapped to: /data/data/org.xbmc.kodi/cache/apk/assets
13:09:08 T:1568347816  NOTICE: special://masterprofile/ is mapped to: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata
13:09:08 T:1568347816  NOTICE: special://home/ is mapped to: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi
13:09:08 T:1568347816  NOTICE: special://temp/ is mapped to: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp
13:09:08 T:1568347816  NOTICE: The executable running is:
13:09:08 T:1568347816  NOTICE: Local hostname: localhost
13:09:08 T:1568347816  NOTICE: Log File is located: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp/kodi.log
13:09:08 T:1568347816  NOTICE: -----------------------------------------------------------------------
13:09:08 T:1568347816  NOTICE: load settings...
13:09:08 T:1568347816   DEBUG: CSettings: loaded settings definition from special://xbmc/system/settings/settings.xml
13:09:08 T:1568347816 WARNING: CSettingInt: unknown options filler "audiocdactions" of "audiocds.autoaction"
13:09:08 T:1568347816   DEBUG: CSettings: loaded settings definition from special://xbmc/system/settings/android.xml
13:09:08 T:1568347816   DEBUG: AESinkAUDIOTRACK - 44100 supported
13:09:08 T:1568347816   DEBUG: AESinkAUDIOTRACK - 48000 supported
13:09:08 T:1568347816  NOTICE: Found 1 Lists of Devices
13:09:08 T:1568347816  NOTICE: Enumerated AUDIOTRACK devices:
13:09:08 T:1568347816  NOTICE:     Device 1
13:09:08 T:1568347816  NOTICE:         m_deviceName      : AudioTrack
13:09:08 T:1568347816  NOTICE:         m_displayName     : android
13:09:08 T:1568347816  NOTICE:         m_displayNameExtra: audiotrack
13:09:08 T:1568347816  NOTICE:         m_deviceType      : AE_DEVTYPE_HDMI
13:09:08 T:1568347816  NOTICE:         m_channels        : FL,FR,FC,LFE,BL,BR
13:09:08 T:1568347816  NOTICE:         m_sampleRates     : 44100,48000
13:09:08 T:1568347816  NOTICE:         m_dataFormats     : AE_FMT_S16LE,AE_FMT_AC3,AE_FMT_DTS
13:09:08 T:1568347816  NOTICE: No settings file to load (special://xbmc/system/advancedsettings.xml)
13:09:08 T:1568347816  NOTICE: Loaded settings file from special://profile/advancedsettings.xml
13:09:08 T:1568347816  NOTICE: Contents of special://profile/advancedsettings.xml are...
                                            <advancedsettings>
                                              <network>
                                                <buffermode>1</buffermode>
                                                <cachemembuffersize>157286400</cachemembuffersize>
                                                <readbufferfactor>20</readbufferfactor>
                                              </network>
                                            </advancedsettings>
13:09:08 T:1568347816  NOTICE: Default DVD Player: dvdplayer
13:09:08 T:1568347816  NOTICE: Default Video Player: dvdplayer
13:09:08 T:1568347816  NOTICE: Default Audio Player: paplayer
13:09:08 T:1568347816  NOTICE: Disabled debug logging due to GUI setting. Level 0.
13:09:08 T:1568347816  NOTICE: Log level changed to "LOG_LEVEL_NORMAL"
13:09:08 T:1568347816  NOTICE: CMediaSourceSettings: loading media sources from special://masterprofile/sources.xml
13:09:08 T:1568347816  NOTICE: Loading player core factory settings from special://xbmc/system/playercorefactory.xml.
13:09:08 T:1568347816  NOTICE: Loaded playercorefactory configuration
13:09:08 T:1568347816  NOTICE: Loading player core factory settings from special://masterprofile/playercorefactory.xml.
13:09:08 T:1568347816  NOTICE: special://masterprofile/playercorefactory.xml does not exist. Skipping.
13:09:08 T:1547453032  NOTICE: Thread ActiveAE start, auto delete: false
13:09:08 T:1547844592  NOTICE: Thread AESink start, auto delete: false
13:09:09 T:1568347816  NOTICE: Running database version Addons19
13:09:09 T:1568347816  NOTICE: ADDONS: Using repository repository.xunitytalk
13:09:09 T:1568347816  NOTICE: ADDONS: Using repository repository.Kinkin
13:09:09 T:1568347816  NOTICE: ADDONS: Using repository repository.xbmchub
13:09:09 T:1568347816  NOTICE: ADDONS: Using repository repository.dextertv
13:09:09 T:1568347816  NOTICE: ADDONS: Using repository repository.i4a-repo
13:09:09 T:1568347816  NOTICE: ADDONS: Using repository repository.xbmc.org
13:09:09 T:1568347816  NOTICE: ADDONS: Using repository repository.metalkettle
13:09:09 T:1568347816  NOTICE: virtual bool CWinSystemEGL::InitWindowSystem(): Using EGL Implementation: android
13:09:09 T:1568347816  NOTICE: Current resolution: 1920x1080 @ 60.00 - Full Screen
13:09:09 T:1568347816  NOTICE: Previous line repeats 1 times.
13:09:09 T:1568347816  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 59.999996 Hz
13:09:09 T:1568347816  NOTICE: Found (1920x1080@59.999996) at 16, setting to RES_DESKTOP at 16
13:09:09 T:1568347816  NOTICE: Checking resolution 16
13:09:09 T:1568347816  NOTICE: Current resolution: 1920x1080 @ 60.00 - Full Screen
13:09:09 T:1568347816  NOTICE: GL_VENDOR = Broadcom
13:09:09 T:1568347816  NOTICE: GL_RENDERER = VideoCore IV HW
13:09:09 T:1568347816  NOTICE: GL_VERSION = OpenGL ES 2.0
13:09:09 T:1568347816  NOTICE: GL_SHADING_LANGUAGE_VERSION = OpenGL ES GLSL ES 1.00
13:09:09 T:1568347816  NOTICE: GL_EXTENSIONS = GL_OES_compressed_ETC1_RGB8_texture GL_OES_compressed_paletted_texture GL_OES_texture_npot GL_OES_depth24 GL_OES_vertex_half_float GL_OES_EGL_image GL_OES_EGL_image_external GL_EXT_discard_framebuffer GL_OES_rgb8_rgba8 GL_OES_depth32 GL_OES_packed_depth_stencil GL_EXT_texture_format_BGRA8888 GL_EXT_debug_marker
13:09:09 T:1568347816  NOTICE: Current resolution: 1920x1080 @ 60.00 - Full Screen
13:09:10 T:1568347816 WARNING: Unable to resolve: /libcec.so CECInitialise, reason: Symbol not found:
13:09:10 T:1568347816   ERROR: Unable to resolve exports from dll libcec.so
13:09:10 T:1568347816   ERROR: virtual void PERIPHERALS::CPeripherals::Initialise() - failed to initialise bus cec
13:09:10 T:1552908776  NOTICE: Thread PeripBusUSB start, auto delete: false
13:09:10 T:1568347816  NOTICE: Running database version Addons19
13:09:10 T:1568347816  NOTICE: Running database version ViewModes6
13:09:10 T:1568347816  NOTICE: Running database version Textures13
13:09:10 T:1568347816  NOTICE: Running database version MyMusic52
13:09:10 T:1568347816  NOTICE: Running database version MyVideos93
13:09:10 T:1568347816  NOTICE: Running database version TV29
13:09:10 T:1568347816  NOTICE: Running database version Epg10
13:09:11 T:1568347816 WARNING: JSONRPC: Could not parse type "PVR.Details.Channel"
13:09:11 T:1568347816 WARNING: JSONRPC: Could not parse type "PVR.Details.ChannelGroup.Extended"
13:09:11 T:1568347816 WARNING: JSONRPC: Could not parse type "GUI.Property.Value"
13:09:11 T:1568347816 WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList"
13:09:11 T:1650253592  NOTICE: Thread LanguageInvoker start, auto delete: false
13:09:11 T:1568347816  NOTICE: Previous line repeats 7 times.
13:09:11 T:1568347816  NOTICE: initialize done
13:09:11 T:1568347816  NOTICE: Running the application...
13:09:11 T:1658845000  NOTICE: Thread LanguageInvoker start, auto delete: false
13:09:12 T:1651303128  NOTICE: -->Python Interpreter Initialized<--
13:09:12 T:1661830576  NOTICE: Previous line repeats 3 times.
13:09:12 T:1661830576  NOTICE: Thread JobWorker start, auto delete: true
13:09:12 T:1661864744  NOTICE: Thread LanguageInvoker start, auto delete: false
13:09:12 T:1568347816  NOTICE: starting zeroconf publishing
13:09:12 T:1568347816  NOTICE: Webserver: Starting...
13:09:12 T:1568347816  NOTICE: WebServer: Started the webserver
13:09:12 T:1664008072  NOTICE: Thread ZerocconfEmbedded start, auto delete: false
13:09:12 T:1664009088  NOTICE: Thread JobWorker start, auto delete: true
13:09:12 T:1568347816  NOTICE: starting upnp client
13:09:12 T:1568347816  NOTICE: ES: Starting event server
13:09:12 T:1671595608  NOTICE: Thread EventServer start, auto delete: false
13:09:12 T:1671595608  NOTICE: ES: Starting UDP Event server on 0.0.0.0:9777
13:09:12 T:1671595608  NOTICE: UDP: Listening on port 9777
13:09:12 T:1568347816  NOTICE: Current resolution: 1920x1080 @ 60.00 - Full Screen
13:09:12 T:1568347816  NOTICE: GL_VENDOR = Broadcom
13:09:12 T:1568347816  NOTICE: GL_RENDERER = VideoCore IV HW
13:09:12 T:1568347816  NOTICE: GL_VERSION = OpenGL ES 2.0
13:09:12 T:1568347816  NOTICE: GL_SHADING_LANGUAGE_VERSION = OpenGL ES GLSL ES 1.00
13:09:12 T:1568347816  NOTICE: GL_EXTENSIONS = GL_OES_compressed_ETC1_RGB8_texture GL_OES_compressed_paletted_texture GL_OES_texture_npot GL_OES_depth24 GL_OES_vertex_half_float GL_OES_EGL_image GL_OES_EGL_image_external GL_EXT_discard_framebuffer GL_OES_rgb8_rgba8 GL_OES_depth32 GL_OES_packed_depth_stencil GL_EXT_texture_format_BGRA8888 GL_EXT_debug_marker

**Comment by scareyman** [comment]
here's the first half of the log file in case it's relevant.

13:09:08 T:1568347816  NOTICE: special://profile/ is mapped to: special://masterprofile/
13:09:08 T:1568347816  NOTICE: -----------------------------------------------------------------------
13:09:08 T:1568347816  NOTICE: Starting Kodi (15.2 Git:2015-10-27-17fa8da). Platform: Android ARM 32-bit
13:09:08 T:1568347816  NOTICE: Using Release Kodi x32 build
13:09:08 T:1568347816  NOTICE: Kodi compiled Oct 27 2015 by GCC 4.8.0 for Android ARM 32-bit API level 17 (API level 17)
13:09:08 T:1568347816  NOTICE: Running on Amazon AFTM with Android 4.2.2 API level 17, kernel: Linux ARM 32-bit version 3.0.31+
13:09:08 T:1568347816  NOTICE: FFmpeg version: 2.6.4-kodi-2.6.4-Isengard
13:09:08 T:1568347816  NOTICE: Host CPU: ARMv7 Processor rev 0 (v7l), 2 cores available
13:09:08 T:1568347816  NOTICE: Product: montoya, Device: montoya, Board: capri - Manufacturer: Amazon, Brand: BRCM, Model: AFTM, Hardware: montoya
13:09:08 T:1568347816  NOTICE: External storage path = /storage/emulated/0; status = ok
13:09:08 T:1568347816  NOTICE: ARM Features: Neon enabled
13:09:08 T:1568347816  NOTICE: special://xbmc/ is mapped to: /data/data/org.xbmc.kodi/cache/apk/assets
13:09:08 T:1568347816  NOTICE: special://xbmcbin/ is mapped to: /data/data/org.xbmc.kodi/cache/apk/assets
13:09:08 T:1568347816  NOTICE: special://masterprofile/ is mapped to: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata
13:09:08 T:1568347816  NOTICE: special://home/ is mapped to: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi
13:09:08 T:1568347816  NOTICE: special://temp/ is mapped to: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp
13:09:08 T:1568347816  NOTICE: The executable running is:
13:09:08 T:1568347816  NOTICE: Local hostname: localhost
13:09:08 T:1568347816  NOTICE: Log File is located: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp/kodi.log
13:09:08 T:1568347816  NOTICE: -----------------------------------------------------------------------
13:09:08 T:1568347816  NOTICE: load settings...
13:09:08 T:1568347816   DEBUG: CSettings: loaded settings definition from special://xbmc/system/settings/settings.xml
13:09:08 T:1568347816 WARNING: CSettingInt: unknown options filler "audiocdactions" of "audiocds.autoaction"
13:09:08 T:1568347816   DEBUG: CSettings: loaded settings definition from special://xbmc/system/settings/android.xml
13:09:08 T:1568347816   DEBUG: AESinkAUDIOTRACK - 44100 supported
13:09:08 T:1568347816   DEBUG: AESinkAUDIOTRACK - 48000 supported
13:09:08 T:1568347816  NOTICE: Found 1 Lists of Devices
13:09:08 T:1568347816  NOTICE: Enumerated AUDIOTRACK devices:
13:09:08 T:1568347816  NOTICE:     Device 1
13:09:08 T:1568347816  NOTICE:         m_deviceName      : AudioTrack
13:09:08 T:1568347816  NOTICE:         m_displayName     : android
13:09:08 T:1568347816  NOTICE:         m_displayNameExtra: audiotrack
13:09:08 T:1568347816  NOTICE:         m_deviceType      : AE_DEVTYPE_HDMI
13:09:08 T:1568347816  NOTICE:         m_channels        : FL,FR,FC,LFE,BL,BR
13:09:08 T:1568347816  NOTICE:         m_sampleRates     : 44100,48000
13:09:08 T:1568347816  NOTICE:         m_dataFormats     : AE_FMT_S16LE,AE_FMT_AC3,AE_FMT_DTS
13:09:08 T:1568347816  NOTICE: No settings file to load (special://xbmc/system/advancedsettings.xml)
13:09:08 T:1568347816  NOTICE: Loaded settings file from special://profile/advancedsettings.xml
13:09:08 T:1568347816  NOTICE: Contents of special://profile/advancedsettings.xml are...
                                            <advancedsettings>
                                              <network>
                                                <buffermode>1</buffermode>
                                                <cachemembuffersize>157286400</cachemembuffersize>
                                                <readbufferfactor>20</readbufferfactor>
                                              </network>
                                            </advancedsettings>
13:09:08 T:1568347816  NOTICE: Default DVD Player: dvdplayer
13:09:08 T:1568347816  NOTICE: Default Video Player: dvdplayer
13:09:08 T:1568347816  NOTICE: Default Audio Player: paplayer
13:09:08 T:1568347816  NOTICE: Disabled debug logging due to GUI setting. Level 0.
13:09:08 T:1568347816  NOTICE: Log level changed to "LOG_LEVEL_NORMAL"
13:09:08 T:1568347816  NOTICE: CMediaSourceSettings: loading media sources from special://masterprofile/sources.xml
13:09:08 T:1568347816  NOTICE: Loading player core factory settings from special://xbmc/system/playercorefactory.xml.
13:09:08 T:1568347816  NOTICE: Loaded playercorefactory configuration
13:09:08 T:1568347816  NOTICE: Loading player core factory settings from special://masterprofile/playercorefactory.xml.
13:09:08 T:1568347816  NOTICE: special://masterprofile/playercorefactory.xml does not exist. Skipping.
13:09:08 T:1547453032  NOTICE: Thread ActiveAE start, auto delete: false
13:09:08 T:1547844592  NOTICE: Thread AESink start, auto delete: false
13:09:09 T:1568347816  NOTICE: Running database version Addons19
13:09:09 T:1568347816  NOTICE: ADDONS: Using repository repository.xunitytalk
13:09:09 T:1568347816  NOTICE: ADDONS: Using repository repository.Kinkin
13:09:09 T:1568347816  NOTICE: ADDONS: Using repository repository.xbmchub
13:09:09 T:1568347816  NOTICE: ADDONS: Using repository repository.dextertv
13:09:09 T:1568347816  NOTICE: ADDONS: Using repository repository.i4a-repo
13:09:09 T:1568347816  NOTICE: ADDONS: Using repository repository.xbmc.org
13:09:09 T:1568347816  NOTICE: ADDONS: Using repository repository.metalkettle
13:09:09 T:1568347816  NOTICE: virtual bool CWinSystemEGL::InitWindowSystem(): Using EGL Implementation: android
13:09:09 T:1568347816  NOTICE: Current resolution: 1920x1080 @ 60.00 - Full Screen
13:09:09 T:1568347816  NOTICE: Previous line repeats 1 times.
13:09:09 T:1568347816  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 59.999996 Hz
13:09:09 T:1568347816  NOTICE: Found (1920x1080@59.999996) at 16, setting to RES_DESKTOP at 16
13:09:09 T:1568347816  NOTICE: Checking resolution 16
13:09:09 T:1568347816  NOTICE: Current resolution: 1920x1080 @ 60.00 - Full Screen
13:09:09 T:1568347816  NOTICE: GL_VENDOR = Broadcom
13:09:09 T:1568347816  NOTICE: GL_RENDERER = VideoCore IV HW
13:09:09 T:1568347816  NOTICE: GL_VERSION = OpenGL ES 2.0
13:09:09 T:1568347816  NOTICE: GL_SHADING_LANGUAGE_VERSION = OpenGL ES GLSL ES 1.00
13:09:09 T:1568347816  NOTICE: GL_EXTENSIONS = GL_OES_compressed_ETC1_RGB8_texture GL_OES_compressed_paletted_texture GL_OES_texture_npot GL_OES_depth24 GL_OES_vertex_half_float GL_OES_EGL_image GL_OES_EGL_image_external GL_EXT_discard_framebuffer GL_OES_rgb8_rgba8 GL_OES_depth32 GL_OES_packed_depth_stencil GL_EXT_texture_format_BGRA8888 GL_EXT_debug_marker
13:09:09 T:1568347816  NOTICE: Current resolution: 1920x1080 @ 60.00 - Full Screen
13:09:10 T:1568347816 WARNING: Unable to resolve: /libcec.so CECInitialise, reason: Symbol not found:
13:09:10 T:1568347816   ERROR: Unable to resolve exports from dll libcec.so
13:09:10 T:1568347816   ERROR: virtual void PERIPHERALS::CPeripherals::Initialise() - failed to initialise bus cec
13:09:10 T:1552908776  NOTICE: Thread PeripBusUSB start, auto delete: false
13:09:10 T:1568347816  NOTICE: Running database version Addons19
13:09:10 T:1568347816  NOTICE: Running database version ViewModes6
13:09:10 T:1568347816  NOTICE: Running database version Textures13
13:09:10 T:1568347816  NOTICE: Running database version MyMusic52
13:09:10 T:1568347816  NOTICE: Running database version MyVideos93
13:09:10 T:1568347816  NOTICE: Running database version TV29
13:09:10 T:1568347816  NOTICE: Running database version Epg10
13:09:11 T:1568347816 WARNING: JSONRPC: Could not parse type "PVR.Details.Channel"
13:09:11 T:1568347816 WARNING: JSONRPC: Could not parse type "PVR.Details.ChannelGroup.Extended"
13:09:11 T:1568347816 WARNING: JSONRPC: Could not parse type "GUI.Property.Value"
13:09:11 T:1568347816 WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList"
13:09:11 T:1650253592  NOTICE: Thread LanguageInvoker start, auto delete: false
13:09:11 T:1568347816  NOTICE: Previous line repeats 7 times.
13:09:11 T:1568347816  NOTICE: initialize done
13:09:11 T:1568347816  NOTICE: Running the application...
13:09:11 T:1658845000  NOTICE: Thread LanguageInvoker start, auto delete: false
13:09:12 T:1651303128  NOTICE: -->Python Interpreter Initialized<--
13:09:12 T:1661830576  NOTICE: Previous line repeats 3 times.
13:09:12 T:1661830576  NOTICE: Thread JobWorker start, auto delete: true
13:09:12 T:1661864744  NOTICE: Thread LanguageInvoker start, auto delete: false
13:09:12 T:1568347816  NOTICE: starting zeroconf publishing
13:09:12 T:1568347816  NOTICE: Webserver: Starting...
13:09:12 T:1568347816  NOTICE: WebServer: Started the webserver
13:09:12 T:1664008072  NOTICE: Thread ZerocconfEmbedded start, auto delete: false
13:09:12 T:1664009088  NOTICE: Thread JobWorker start, auto delete: true
13:09:12 T:1568347816  NOTICE: starting upnp client
13:09:12 T:1568347816  NOTICE: ES: Starting event server
13:09:12 T:1671595608  NOTICE: Thread EventServer start, auto delete: false
13:09:12 T:1671595608  NOTICE: ES: Starting UDP Event server on 0.0.0.0:9777
13:09:12 T:1671595608  NOTICE: UDP: Listening on port 9777
13:09:12 T:1568347816  NOTICE: Current resolution: 1920x1080 @ 60.00 - Full Screen
13:09:12 T:1568347816  NOTICE: GL_VENDOR = Broadcom
13:09:12 T:1568347816  NOTICE: GL_RENDERER = VideoCore IV HW
13:09:12 T:1568347816  NOTICE: GL_VERSION = OpenGL ES 2.0
13:09:12 T:1568347816  NOTICE: GL_SHADING_LANGUAGE_VERSION = OpenGL ES GLSL ES 1.00
13:09:12 T:1568347816  NOTICE: GL_EXTENSIONS = GL_OES_compressed_ETC1_RGB8_texture GL_OES_compressed_paletted_texture GL_OES_texture_npot GL_OES_depth24 GL_OES_vertex_half_float GL_OES_EGL_image GL_OES_EGL_image_external GL_EXT_discard_framebuffer GL_OES_rgb8_rgba8 GL_OES_depth32 GL_OES_packed_depth_stencil GL_EXT_texture_format_BGRA8888 GL_EXT_debug_marker

**Comment by scareyman** [comment]
I *think* I solved this issue by replacing this (at line 620ish of client.py):
I *think* I solved this issue by replacing this (at line 620ish of client.py):
      try:
        data['token_expiry'] = datetime.datetime.strptime(
            data['token_expiry'], EXPIRY_FORMAT)

with this:

      try:
        data['token_expiry'] = datetime.datetime.strptime(
            time.strptime(data['token_expiry']), EXPIRY_FORMAT)

**Comment by robweber** [comment]
Going to close this as that is a dependent addon (plus this is really old)
