### ISSUE TITLE
Backing up to External MicroSD card

### ISSUE THREAD

**Issue by rankl2609** [robweber/xbmcbackup#80]
First, I have to admit that I'm a newbie to Kodi/XBMC.  I have done extensive Google searches and I've found a few leads that might indicate a firmware problem?  I have a rooted Android TV box (running 5.1.1), and when I try to run the XBMCbackup to my external SD card, I get a "Write Error Detected" popup indicationg that the destination may not be writeable.  But I am able to write to it outside of Kodi using ES File Explorer.  Is there any fix for this?  I am running Kodi version 16.0...  it just updated today.
Here is the link to my log:  http://xbmclogs.com/pgmnfjibp

**Comment by robweber** [comment]
Closing since no movement here. I imagine it's an OS permissions thing.
