### ISSUE TITLE
[REQUEST] Backup tv and movies addon_data

### ISSUE THREAD

**Issue by eddavidson** [robweber/xbmcbackup#81]
Hi Rob,

I hope i'm not to late to request this but I had an idea. Since most users only want their favorites and library entries backed up, how about adding an option that only backs up certain addons like the list could be backup: 
Istream script.module.universal (istream favs)
script.icechannel (Istream Library)
1Channel
TV online
SALTS
Super Favorites
etc, etc

**Comment by robweber** [comment]
Good idea. I plan on making the selectable files much more comprehensive in V2

**Comment by robweber** [comment]
Going to close this, but not because it's invalid. I'm merging a lot of issues into on PR https://github.com/robweber/xbmcbackup/pull/117
