### ISSUE TITLE
Backup fails if using compressiong and thumbnails/fanart

### ISSUE THREAD

**Issue by dairefagan** [robweber/xbmcbackup#84]
My backups are quite large, the latest 3.8GB, but when I try to use the backup compression option the backup fails and the following errors are generated in the log:

http://xbmclogs.com/pycw8uz1t

Since testing initially I have worked out that compression backup only fails if I have thumbnails/fanart selected, if I deselect thumbnails/fanart and leave everything else selected apart from custom dirs it works just fine. I run Kodi on an Nvidia Shield with 500GB HDD so there should be no issue with space.

**Comment by robweber** [comment]
I realize this is pretty old but the log no longer works. Sorry for the delay, if you want to reload the log file I'll take a look.

**Comment by robweber** [comment]
going to close as there isn't a log anymore. Re-open if in error.
