### ISSUE TITLE
Split files larger than 4GB

### ISSUE THREAD

**Issue by helderk** [robweber/xbmcbackup#85]
I keep my backups on a local disk formatted in FAT32, but my backup files are already too large to be written in the disk, it returns write error.
It would be useful an option that automatically split files larger than 4GB.

**Comment by robweber** [comment]
going to add this to the "wish list" for v2.

**Comment by robweber** [comment]
Going to close this out as V2 is pretty much complete and functional at this point.  I don't think I'll add this as watching the grow rate of the zip file and splitting it is beyond the scope of low level file management I want to do. Most of the file functionality is being passed off to Kodi specific methods as it is.
