### ISSUE TITLE
Dropbox Python SDK certificate expiring

### ISSUE THREAD

**Issue by ricksebak** [robweber/xbmcbackup#86]
Hi,

I got the following email from Dropbox, warning me that some changes they are making will break the Kodi backup plugin. Can you tell me if this is planned to be fixed in a future release? I'm currently on version 1.0.6.

> We're writing to you because our logs indicate that you have at least one Dropbox API app (mediacenter_kodi_backup) using an old version of the Python Core SDK, with an out of date certificate file. 
> 
> The Dropbox Python Core SDK implements certificate pinning, based on a list of certificates included in the SDK, in order to help secure the connection to the Dropbox API servers. 
> 
> On August 1st, 2016, the Dropbox API servers will be updated to use a new certificate, so you’ll need to update the version of the SDK used in your app to match. The latest version of the Python Core SDK already contains the updated certificate file:
> 
> https://www.dropbox.com/developers-v1/core/sdks/python
> 
> You can refer to the CHANGELOG file included in the SDK for a list of changes.
> 
> Please update your app to use the latest SDK by 8/1/16 to ensure continued access to the Dropbox API.
> 
> Thanks!

**Comment by robweber** [comment]
Wow, looks like I missed that date! 

I'm going to check into the new API or at least making sure I can get an updated cert for current versions of the addon.

**Comment by robweber** [comment]
Fixed with 622039febb77f7c090d675414dfdbfc41ac1c8a2
