### ISSUE TITLE
Dropbox Destination not Writable

### ISSUE THREAD

**Issue by broyuken** [robweber/xbmcbackup#88]
Hello,

Using the latest stable version of Kodi, and the most recent version of the backup addon on a fire tv stick running Fire OS 5.3.2.1 I cannot write to dropbox. It was working for a daily backup, then for some reason on the 23rd it stopped working. I tried deleting the dropbox app and the backup app and starting from scratch but I still have the same issue. 

I get the error:

"WRITE ERROR DETECTED
The destination may not be writeable
Zip archive could not be copied"

Here is my log with personal info removed:
07:11:08 T:18446744072562719424  NOTICE: script.xbmcbackup-1.0.6: Authorize URL: https://www.dropbox.com/1/oauth/authorize?oauth_token=bb9kVNRQXSSRepwr
07:11:52 T:18446744072562719424  NOTICE: script.xbmcbackup-1.0.6: {u'referral_link': u'https://db.tt/E4e4X3u4CB', u'display_name': u'********', u'uid': 1130007, u'locale': u'en', u'email_verified': True, u'email': u'*********@gmail.com', u'is_paired': False, u'team': None, u'name_details': {u'familiar_name': u'*****', u'surname': u'***', u'given_name': u'******'}, u'country': u'US', u'quota_info': {u'datastores': 0, u'shared': 9360037595L, u'quota': 24536678400L, u'normal': 5175860375L}}
07:11:52 T:18446744072562719424  NOTICE: script.xbmcbackup-1.0.6: Starting
07:11:52 T:18446744072562719424  NOTICE: script.xbmcbackup-1.0.6: Local Dir: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/
07:11:52 T:18446744072562719424  NOTICE: script.xbmcbackup-1.0.6: Remote Dir: 201612280711/
07:11:52 T:18446744072562719424  NOTICE: script.xbmcbackup-1.0.6: Mode - Backup
07:11:52 T:18446744072562719424  NOTICE: script.xbmcbackup-1.0.6: Creating Files List
07:12:07 T:18446744072562719424  NOTICE: script.xbmcbackup-1.0.6: Writing files to: 201612280711/
07:12:07 T:18446744072562719424  NOTICE: script.xbmcbackup-1.0.6: Source: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/
07:15:10 T:18446744072562719424  NOTICE: script.xbmcbackup-1.0.6: Writing files to: /
07:15:10 T:18446744072562719424  NOTICE: script.xbmcbackup-1.0.6: Source: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp/

**Comment by broyuken** [comment]
Bueller?

**Comment by robweber** [comment]
It looks like the application was unauthorized (or never properly authorized). See the authorize URL in the log file? 

This addon does not rely on the Dropbox Kodi Addon, it uses the dropbox python libraries directly and must be authorized separate.

**Comment by broyuken** [comment]
I did launch the authorize URL from the logs, and give it access to my dropbox. I am also having trouble getting this to work with a local smb backup. 


15:06:40 T:11700  NOTICE: script.xbmcbackup-1.0.6: extracting zip archive
15:07:01 T:11700   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: argument 1 must be string, not int
                                            Traceback (most recent call last):
                                              File "C:\Users\broy\AppData\Roaming\Kodi\addons\script.xbmcbackup\default.py", line 73, in <module>
                                                backup.run(mode)
                                              File "C:\Users\broy\AppData\Roaming\Kodi\addons\script.xbmcbackup\resources\lib\backup.py", line 319, in run
                                                xbmcgui.Dialog.ok(utils.getSetting(30010),utils.getString(30101))
                                              File "C:\Users\broy\AppData\Roaming\Kodi\addons\script.xbmcbackup\resources\lib\utils.py", line 24, in getSetting
                                                return __Addon.getSetting(name)
                                            TypeError: argument 1 must be string, not int
                                            -->End of Python script error report<--

**Comment by broyuken** [comment]
Also when I say I deleted the dropbox app, I mean I deleted my app from the developer portal on dropbox.com, not a Kodi app.

**Comment by robweber** [comment]
Ok, gotcha. 

I did just do a push on a fix for the issue with line 319 in the backup.py file that is causing the getSetting() error. I'll push to the repo once I finish clearing up the rest of the outstanding issues or you can do a manual download to test.

**Comment by robweber** [comment]
I did push the proposed fix to this for the repo for versions 1.0.8 and 1.0.9 (current). Any word on if this worked for you? I'll leave this open for a few days and then assume fixed.

**Comment by broyuken** [comment]
Hi, sorry I've been pretty busy lately and haven't been home to test. I did give up on Dropbox after the issue was discovered and moved to smb. When I get a chance I'll switch it back to Dropbox and see if it's any better. If it's not I'll open a new issue and reference this one.

**Comment by robweber** [comment]
Sounds great. Thanks for the response.
