### ISSUE TITLE
Restore can not handle umlaute

### ISSUE THREAD

**Issue by crispyduck00** [robweber/xbmcbackup#91]
When having Kodi language set to German and the region to Österreich (Austria) the restore process always fails because of the umlaut Ö.

**Comment by robweber** [comment]
My best guess here is that this is happening when the settings are being restored with the SetSetting JSON call, but I'd like a little more info to be sure. Can you post the log to something like pastebin and post the link here?

**Comment by crispyduck00** [comment]
I don't have the log anymore. 
I will retest it on Weekend and post it.

**Comment by robweber** [comment]
Great - thank you. It could be one of a few places the error is being thrown. Just want to be sure before I go trying things.

**Comment by crispyduck00** [comment]
Here the log from another restore with region set to Österreich: [http://pastebin.com/raw/xWc9A6P0](url)

**Comment by crispyduck00** [comment]
Here the log from another restore with Region set to Österreich: [http://pastebin.com/raw/xWc9A6P0](url)

**Comment by robweber** [comment]
Perfect. That's exactly where I expected the error to occur but wanted to be sure with your system that was the case. I'll work on a fix.

**Comment by crispyduck00** [comment]
Thanks foryour great work!
If you need anything else or a tester, let me know.

**Comment by robweber** [comment]
If you could please try this branch, I think I've fixed this problem https://github.com/robweber/xbmcbackup/tree/settings_utf_error 

if you don't want to download the whole thing, here is the changed file: https://github.com/robweber/xbmcbackup/blob/settings_utf_error/resources/lib/guisettings.py

**Comment by crispyduck00** [comment]
I will try it as soon as possible in the next days.

**Comment by robweber** [comment]
I'm going to merge this in, pretty sure this is the fix needed here.
