### ISSUE TITLE
Error after Backup update 1.08 on Fire TV Stick

### ISSUE THREAD

**Issue by kodi8r** [robweber/xbmcbackup#94]
Backup addon was fine until auto-update 1.08. Now, an error pops up at KODI start-up and addon will no longer open. This issue is not happenning in Windows Laptop. It seems it's only affected in android (Fire TV Stick). FYI I use the Backup addon constantly to both backup and restore builds and it rocks!

**Comment by WillieHeckerslyke** [comment]
Yep, can confirm this issue also on v1.0.8 on a Shield TV (2017). Only happens when trying to actually run the addon - I can enter the Settings without any errors though...

**Comment by robweber** [comment]
the only major thing that happened with 1.08 was the update to the Dropbox API. I don't have a fireTV stick, is the Shield TV android based as well? Could be it only affects that. If you could get a log that would really help. The systems I tested it on (Windows, LibreElec) worked for me.

**Comment by koying** [comment]
Problem is at https://github.com/robweber/xbmcbackup/blob/master/resources/lib/dropbox/rest.py#L415

Here is the root cause: http://stackoverflow.com/questions/27025046/dropbox-python-api-import-dropbox-syntax-error
Android and RPI Jarvis stil use 2.6

Here is a solution: http://stackoverflow.com/questions/21069668/alternative-to-dict-comprehension-prior-to-python-2-7

Here is a alternative definition of this function which, at 1st sight, would work on 2.6

```
def params_to_urlencoded(params):
    """
    Returns a application/x-www-form-urlencoded 'str' representing the key/value pairs in 'params'.
    
    Keys are values are str()'d before calling urllib.urlencode, with the exception of unicode
    objects which are utf8-encoded.
    """
    def encode(o):
        if isinstance(o, unicode):
            return o.encode('utf8')
        else:
            return str(o)
    utf8_params={}
    for k, v in params.iteritems():
        utf8_params[encode(k)]= encode(v)
    return urllib.urlencode(utf8_params)
````

**Comment by robweber** [comment]
Thanks for the detailed response! I vaguely remembered Android being a different python version from an issue in the past, thought that might be the problem here too.

**Comment by robweber** [comment]
That fix for python 2.6 looks like it will work to me too. I patched and tried on Windows (I know 2.7 but just wanted to make sure the code was solid). I didn't have any issues. 

Putting out a call here for anyone with an Android or RPI to try this branch https://github.com/robweber/xbmcbackup/tree/dropbox_2.6 or just replace the [rest.py](https://github.com/robweber/xbmcbackup/blob/dropbox_2.6/resources/lib/dropbox/rest.py) file.

**Comment by pettergul** [comment]
Changing the rest.py inside Dropbox folder worked nice for me on NSTV. With the latest SPMC official.

**Comment by ieswideopen** [comment]
Will there be an update on this for android users?

**Comment by ieswideopen** [comment]
Will there be an update on this for android users?

**Comment by robweber** [comment]
Yes, after I closed the issue I created a pull request with this fix on the official repo. Looks like it's already been pulled: https://github.com/xbmc/repo-scripts/pull/374

**Comment by ieswideopen** [comment]
The patch worked on my 3 Android boxes
